# Configuration for formatters can be found here:
# https://github.com/numtide/treefmt-nix/tree/main/programs

[formatter.alejandra]
command = "alejandra"
includes = ["*.nix"]
priority = 1

[formatter.deadnix]
command = "deadnix"
options = ["-e"]
includes = ["*.nix"]
priority = 2

[formatter.gofmt]
command = "gofmt"
options = ["-w"]
includes = ["*.go"]
excludes = ["vendor/*"]

[formatter.goimports]
command = "goimports"
options = ["-w"]
includes = ["*.go"]
excludes = ["vendor/*"]

[formatter.deno]
command = "deno"
options = ["fmt"]
includes = [
  "*.css",
  "*.html",
  "*.js",
  "*.json",
  "*.jsonc",
  "*.jsx",
  "*.less",
  "*.markdown",
  "*.md",
  "*.sass",
  "*.scss",
  "*.ts",
  "*.tsx",
  "*.yaml",
  "*.yml"
]

