name: "User Story"
title: "[Feature] "
description: "Create a new user story"
labels: ["type:feature"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Describe the user story in the format: As a [user], I want [goal], so that [benefit]."
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: "Acceptance Criteria"
      description: "List clear, testable conditions that must be met."
      placeholder: |
        - [ ] Condition 1
        - [ ] Condition 2
  - type: textarea
    id: notes
    attributes:
      label: "Additional Notes"
      description: "Any relevant context, design links, or related issues."
