name: "Epic"
title: "[Epic] "
description: "Large body of work broken down into stories/tasks"
labels: ["type:epic"]
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > Please add appropriate **area**, **priority**, and **size** labels before submitting this issue.

        Use this template to track a big initiative composed of multiple user stories, tasks, or bugs.
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "What is this epic about? Why is it important?"
  - type: textarea
    id: goals
    attributes:
      label: "Goals"
      description: "What does this epic aim to achieve?"
      placeholder: |
        - Goal 1
        - Goal 2
  - type: textarea
    id: scope
    attributes:
      label: "Scope / Deliverables"
      description: "What’s included and what’s explicitly out of scope?"
  - type: textarea
    id: child-issues
    attributes:
      label: "Linked Issues"
      description: "Reference related stories, tasks, or bugs (e.g., #123, #124)."
