name: "Documentation"
title: "[Docs] "
description: "Create or update documentation"
labels: ["type:documentation"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "What needs to be documented or updated? Why is it important?"
  - type: textarea
    id: audience
    attributes:
      label: "Intended Audience"
      description: "Who is this documentation for? (e.g., developers, designers, end-users)"
  - type: textarea
    id: location
    attributes:
      label: "Documentation Location"
      description: "Where should this documentation live? (link to file, wiki, or repo section)"
