name: "Discussion"
description: "Propose an idea or start a technical/product conversation"
labels: ["type:discussion"]
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > Please add appropriate **area**, **priority**, and **size** labels before submitting this issue.
  - type: markdown
    attributes:
      value: |
        ### Discussion
        Use this template to capture ideas, questions, or proposals before turning them into actionable work.
  - type: input
    id: title
    attributes:
      label: "Discussion Title"
      description: "Short, descriptive title."
      placeholder: "e.g. Should we migrate to React Query?"
  - type: textarea
    id: context
    attributes:
      label: "Context"
      description: "What’s the background? Why is this worth discussing?"
  - type: textarea
    id: proposal
    attributes:
      label: "Proposal / Options"
      description: "Outline your suggested approach or list possible options."
  - type: textarea
    id: pros-cons
    attributes:
      label: "Pros & Cons"
      description: "What are the trade-offs?"
      placeholder: |
        **Pros**
        - ...
        
        **Cons**
        - ...
