name: "Discussion"
title: "[Discussion] "
description: "Propose an idea or start a technical/product conversation"
labels: ["type:discussion"]
body:
  - type: textarea
    id: context
    attributes:
      label: "Context"
      description: "What’s the background? Why is this worth discussing?"
  - type: textarea
    id: proposal
    attributes:
      label: "Proposal / Options"
      description: "Outline your suggested approach or list possible options."
  - type: textarea
    id: pros-cons
    attributes:
      label: "Pros & Cons"
      description: "What are the trade-offs?"
      placeholder: |
        **Pros**
        - ...
        
        **Cons**
        - ...
