# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@astrojs/compiler-2.13.0" = {
      name = "_at_astrojs_slash_compiler";
      packageName = "@astrojs/compiler";
      version = "2.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@astrojs/compiler/-/compiler-2.13.0.tgz";
        sha512 = "mqVORhUJViA28fwHYaWmsXSzLO9osbdZ5ImUfxBarqsYdMlPbqAqGJCxsNzvppp1BEzc1mJNjOVvQqeDN8Vspw==";
      };
    };
    "@augment-vir/assert-31.43.0" = {
      name = "_at_augment-vir_slash_assert";
      packageName = "@augment-vir/assert";
      version = "31.43.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@augment-vir/assert/-/assert-31.43.0.tgz";
        sha512 = "h5bJaraz2s1gRYvpDPXZxVkS1qencDwN19So3VNVfMkHnNt69wG88av7SSC1Hj5SUwpaN5sJuFmEYjMIQzkTmQ==";
      };
    };
    "@augment-vir/common-31.43.0" = {
      name = "_at_augment-vir_slash_common";
      packageName = "@augment-vir/common";
      version = "31.43.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@augment-vir/common/-/common-31.43.0.tgz";
        sha512 = "O2gWqQ5UUJSj82AvI1/kWswQodsmnNKz+cvaeCtGtV7i/FrvsduyPfi3/IRfEayL3cn24yymy2ehdwndIebQLg==";
      };
    };
    "@augment-vir/core-31.43.0" = {
      name = "_at_augment-vir_slash_core";
      packageName = "@augment-vir/core";
      version = "31.43.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@augment-vir/core/-/core-31.43.0.tgz";
        sha512 = "VUkQu985HO6EWtkFbEnqw+u9lYG7K0XkQ2jzIaSxJAdsuFu/XltAV4sbFN/Z2s9LGN4+YeqWQSGg1JWscgOrzQ==";
      };
    };
    "@babel/code-frame-7.27.1" = {
      name = "_at_babel_slash_code-frame";
      packageName = "@babel/code-frame";
      version = "7.27.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/code-frame/-/code-frame-7.27.1.tgz";
        sha512 = "cjQ7ZlQ0Mv3b47hABuTevyTuYN4i+loJKGeV9flcCgIK37cCXRh+L1bd3iBHlynerhQ7BhCkn2BPbQUL+rGqFg==";
      };
    };
    "@babel/compat-data-7.28.4" = {
      name = "_at_babel_slash_compat-data";
      packageName = "@babel/compat-data";
      version = "7.28.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/compat-data/-/compat-data-7.28.4.tgz";
        sha512 = "YsmSKC29MJwf0gF8Rjjrg5LQCmyh+j/nD8/eP7f+BeoQTKYqs9RoWbjGOdy0+1Ekr68RJZMUOPVQaQisnIo4Rw==";
      };
    };
    "@babel/core-7.28.4" = {
      name = "_at_babel_slash_core";
      packageName = "@babel/core";
      version = "7.28.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/core/-/core-7.28.4.tgz";
        sha512 = "2BCOP7TN8M+gVDj7/ht3hsaO/B/n5oDbiAyyvnRlNOs+u1o+JWNYTQrmpuNp1/Wq2gcFrI01JAW+paEKDMx/CA==";
      };
    };
    "@babel/generator-7.28.3" = {
      name = "_at_babel_slash_generator";
      packageName = "@babel/generator";
      version = "7.28.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/generator/-/generator-7.28.3.tgz";
        sha512 = "3lSpxGgvnmZznmBkCRnVREPUFJv2wrv9iAoFDvADJc0ypmdOxdUtcLeBgBJ6zE0PMeTKnxeQzyk0xTBq4Ep7zw==";
      };
    };
    "@babel/helper-annotate-as-pure-7.27.3" = {
      name = "_at_babel_slash_helper-annotate-as-pure";
      packageName = "@babel/helper-annotate-as-pure";
      version = "7.27.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-annotate-as-pure/-/helper-annotate-as-pure-7.27.3.tgz";
        sha512 = "fXSwMQqitTGeHLBC08Eq5yXz2m37E4pJX1qAU1+2cNedz/ifv/bVXft90VeSav5nFO61EcNgwr0aJxbyPaWBPg==";
      };
    };
    "@babel/helper-compilation-targets-7.27.2" = {
      name = "_at_babel_slash_helper-compilation-targets";
      packageName = "@babel/helper-compilation-targets";
      version = "7.27.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-compilation-targets/-/helper-compilation-targets-7.27.2.tgz";
        sha512 = "2+1thGUUWWjLTYTHZWK1n8Yga0ijBz1XAhUXcKy81rd5g6yh7hGqMp45v7cadSbEHc9G3OTv45SyneRN3ps4DQ==";
      };
    };
    "@babel/helper-create-class-features-plugin-7.28.3" = {
      name = "_at_babel_slash_helper-create-class-features-plugin";
      packageName = "@babel/helper-create-class-features-plugin";
      version = "7.28.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-create-class-features-plugin/-/helper-create-class-features-plugin-7.28.3.tgz";
        sha512 = "V9f6ZFIYSLNEbuGA/92uOvYsGCJNsuA8ESZ4ldc09bWk/j8H8TKiPw8Mk1eG6olpnO0ALHJmYfZvF4MEE4gajg==";
      };
    };
    "@babel/helper-globals-7.28.0" = {
      name = "_at_babel_slash_helper-globals";
      packageName = "@babel/helper-globals";
      version = "7.28.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-globals/-/helper-globals-7.28.0.tgz";
        sha512 = "+W6cISkXFa1jXsDEdYA8HeevQT/FULhxzR99pxphltZcVaugps53THCeiWA8SguxxpSp3gKPiuYfSWopkLQ4hw==";
      };
    };
    "@babel/helper-member-expression-to-functions-7.27.1" = {
      name = "_at_babel_slash_helper-member-expression-to-functions";
      packageName = "@babel/helper-member-expression-to-functions";
      version = "7.27.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-member-expression-to-functions/-/helper-member-expression-to-functions-7.27.1.tgz";
        sha512 = "E5chM8eWjTp/aNoVpcbfM7mLxu9XGLWYise2eBKGQomAk/Mb4XoxyqXTZbuTohbsl8EKqdlMhnDI2CCLfcs9wA==";
      };
    };
    "@babel/helper-module-imports-7.27.1" = {
      name = "_at_babel_slash_helper-module-imports";
      packageName = "@babel/helper-module-imports";
      version = "7.27.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-module-imports/-/helper-module-imports-7.27.1.tgz";
        sha512 = "0gSFWUPNXNopqtIPQvlD5WgXYI5GY2kP2cCvoT8kczjbfcfuIljTbcWrulD1CIPIX2gt1wghbDy08yE1p+/r3w==";
      };
    };
    "@babel/helper-module-transforms-7.28.3" = {
      name = "_at_babel_slash_helper-module-transforms";
      packageName = "@babel/helper-module-transforms";
      version = "7.28.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-module-transforms/-/helper-module-transforms-7.28.3.tgz";
        sha512 = "gytXUbs8k2sXS9PnQptz5o0QnpLL51SwASIORY6XaBKF88nsOT0Zw9szLqlSGQDP/4TljBAD5y98p2U1fqkdsw==";
      };
    };
    "@babel/helper-optimise-call-expression-7.27.1" = {
      name = "_at_babel_slash_helper-optimise-call-expression";
      packageName = "@babel/helper-optimise-call-expression";
      version = "7.27.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-optimise-call-expression/-/helper-optimise-call-expression-7.27.1.tgz";
        sha512 = "URMGH08NzYFhubNSGJrpUEphGKQwMQYBySzat5cAByY1/YgIRkULnIy3tAMeszlL/so2HbeilYloUmSpd7GdVw==";
      };
    };
    "@babel/helper-plugin-utils-7.27.1" = {
      name = "_at_babel_slash_helper-plugin-utils";
      packageName = "@babel/helper-plugin-utils";
      version = "7.27.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-plugin-utils/-/helper-plugin-utils-7.27.1.tgz";
        sha512 = "1gn1Up5YXka3YYAHGKpbideQ5Yjf1tDa9qYcgysz+cNCXukyLl6DjPXhD3VRwSb8c0J9tA4b2+rHEZtc6R0tlw==";
      };
    };
    "@babel/helper-replace-supers-7.27.1" = {
      name = "_at_babel_slash_helper-replace-supers";
      packageName = "@babel/helper-replace-supers";
      version = "7.27.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-replace-supers/-/helper-replace-supers-7.27.1.tgz";
        sha512 = "7EHz6qDZc8RYS5ElPoShMheWvEgERonFCs7IAonWLLUTXW59DP14bCZt89/GKyreYn8g3S83m21FelHKbeDCKA==";
      };
    };
    "@babel/helper-skip-transparent-expression-wrappers-7.27.1" = {
      name = "_at_babel_slash_helper-skip-transparent-expression-wrappers";
      packageName = "@babel/helper-skip-transparent-expression-wrappers";
      version = "7.27.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-skip-transparent-expression-wrappers/-/helper-skip-transparent-expression-wrappers-7.27.1.tgz";
        sha512 = "Tub4ZKEXqbPjXgWLl2+3JpQAYBJ8+ikpQ2Ocj/q/r0LwE3UhENh7EUabyHjz2kCEsrRY83ew2DQdHluuiDQFzg==";
      };
    };
    "@babel/helper-string-parser-7.27.1" = {
      name = "_at_babel_slash_helper-string-parser";
      packageName = "@babel/helper-string-parser";
      version = "7.27.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-string-parser/-/helper-string-parser-7.27.1.tgz";
        sha512 = "qMlSxKbpRlAridDExk92nSobyDdpPijUq2DW6oDnUqd0iOGxmQjyqhMIihI9+zv4LPyZdRje2cavWPbCbWm3eA==";
      };
    };
    "@babel/helper-validator-identifier-7.27.1" = {
      name = "_at_babel_slash_helper-validator-identifier";
      packageName = "@babel/helper-validator-identifier";
      version = "7.27.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-validator-identifier/-/helper-validator-identifier-7.27.1.tgz";
        sha512 = "D2hP9eA+Sqx1kBZgzxZh0y1trbuU+JoDkiEwqhQ36nodYqJwyEIhPSdMNd7lOm/4io72luTPWH20Yda0xOuUow==";
      };
    };
    "@babel/helper-validator-option-7.27.1" = {
      name = "_at_babel_slash_helper-validator-option";
      packageName = "@babel/helper-validator-option";
      version = "7.27.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-validator-option/-/helper-validator-option-7.27.1.tgz";
        sha512 = "YvjJow9FxbhFFKDSuFnVCe2WxXk1zWc22fFePVNEaWJEu8IrZVlda6N0uHwzZrUM1il7NC9Mlp4MaJYbYd9JSg==";
      };
    };
    "@babel/helpers-7.28.4" = {
      name = "_at_babel_slash_helpers";
      packageName = "@babel/helpers";
      version = "7.28.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helpers/-/helpers-7.28.4.tgz";
        sha512 = "HFN59MmQXGHVyYadKLVumYsA9dBFun/ldYxipEjzA4196jpLZd8UjEEBLkbEkvfYreDqJhZxYAWFPtrfhNpj4w==";
      };
    };
    "@babel/parser-7.28.4" = {
      name = "_at_babel_slash_parser";
      packageName = "@babel/parser";
      version = "7.28.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/parser/-/parser-7.28.4.tgz";
        sha512 = "yZbBqeM6TkpP9du/I2pUZnJsRMGGvOuIrhjzC1AwHwW+6he4mni6Bp/m8ijn0iOuZuPI2BfkCoSRunpyjnrQKg==";
      };
    };
    "@babel/plugin-syntax-typescript-7.27.1" = {
      name = "_at_babel_slash_plugin-syntax-typescript";
      packageName = "@babel/plugin-syntax-typescript";
      version = "7.27.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/plugin-syntax-typescript/-/plugin-syntax-typescript-7.27.1.tgz";
        sha512 = "xfYCBMxveHrRMnAWl1ZlPXOZjzkN82THFvLhQhFXFt81Z5HnN+EtUkZhv/zcKpmT3fzmWZB0ywiBrbC3vogbwQ==";
      };
    };
    "@babel/plugin-transform-modules-commonjs-7.27.1" = {
      name = "_at_babel_slash_plugin-transform-modules-commonjs";
      packageName = "@babel/plugin-transform-modules-commonjs";
      version = "7.27.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/plugin-transform-modules-commonjs/-/plugin-transform-modules-commonjs-7.27.1.tgz";
        sha512 = "OJguuwlTYlN0gBZFRPqwOGNWssZjfIUdS7HMYtN8c1KmwpwHFBwTeFZrg9XZa+DFTitWOW5iTAG7tyCUPsCCyw==";
      };
    };
    "@babel/plugin-transform-typescript-7.28.0" = {
      name = "_at_babel_slash_plugin-transform-typescript";
      packageName = "@babel/plugin-transform-typescript";
      version = "7.28.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/plugin-transform-typescript/-/plugin-transform-typescript-7.28.0.tgz";
        sha512 = "4AEiDEBPIZvLQaWlc9liCavE0xRM0dNca41WtBeM3jgFptfUOSG9z0uteLhq6+3rq+WB6jIvUwKDTpXEHPJ2Vg==";
      };
    };
    "@babel/runtime-7.28.4" = {
      name = "_at_babel_slash_runtime";
      packageName = "@babel/runtime";
      version = "7.28.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/runtime/-/runtime-7.28.4.tgz";
        sha512 = "Q/N6JNWvIvPnLDvjlE1OUBLPQHH6l3CltCEsHIujp45zQUSSh8K+gHnaEX45yAT1nyngnINhvWtzN+Nb9D8RAQ==";
      };
    };
    "@babel/template-7.27.2" = {
      name = "_at_babel_slash_template";
      packageName = "@babel/template";
      version = "7.27.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/template/-/template-7.27.2.tgz";
        sha512 = "LPDZ85aEJyYSd18/DkjNh4/y1ntkE5KwUHWTiqgRxruuZL2F1yuHligVHLvcHY2vMHXttKFpJn6LwfI7cw7ODw==";
      };
    };
    "@babel/traverse-7.28.4" = {
      name = "_at_babel_slash_traverse";
      packageName = "@babel/traverse";
      version = "7.28.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/traverse/-/traverse-7.28.4.tgz";
        sha512 = "YEzuboP2qvQavAcjgQNVgsvHIDv6ZpwXvcvjmyySP2DIMuByS/6ioU5G9pYrWHM6T2YDfc7xga9iNzYOs12CFQ==";
      };
    };
    "@babel/types-7.28.4" = {
      name = "_at_babel_slash_types";
      packageName = "@babel/types";
      version = "7.28.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/types/-/types-7.28.4.tgz";
        sha512 = "bkFqkLhh3pMBUQQkpVgWDWq/lqzc2678eUyDlTBhRqhCHFguYYGM0Efga7tYk4TogG/3x0EEl66/OQ+WGbWB/Q==";
      };
    };
    "@date-vir/duration-8.0.0" = {
      name = "_at_date-vir_slash_duration";
      packageName = "@date-vir/duration";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@date-vir/duration/-/duration-8.0.0.tgz";
        sha512 = "zuliBiCkSdmTTZZAYrKXB70X6SbY0iN3xaO+E0pA2tVp+zyDCdOJfhY4XSkUyIBhp7aF2HC/C2xVOIJ3n/5h8A==";
      };
    };
    "@ianvs/prettier-plugin-sort-imports-4.7.0" = {
      name = "_at_ianvs_slash_prettier-plugin-sort-imports";
      packageName = "@ianvs/prettier-plugin-sort-imports";
      version = "4.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ianvs/prettier-plugin-sort-imports/-/prettier-plugin-sort-imports-4.7.0.tgz";
        sha512 = "soa2bPUJAFruLL4z/CnMfSEKGznm5ebz29fIa9PxYtu8HHyLKNE1NXAs6dylfw1jn/ilEIfO2oLLN6uAafb7DA==";
      };
    };
    "@jridgewell/gen-mapping-0.3.13" = {
      name = "_at_jridgewell_slash_gen-mapping";
      packageName = "@jridgewell/gen-mapping";
      version = "0.3.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/gen-mapping/-/gen-mapping-0.3.13.tgz";
        sha512 = "2kkt/7niJ6MgEPxF0bYdQ6etZaA+fQvDcLKckhy1yIQOzaoKjBBjSj63/aLVjYE3qhRt5dvM+uUyfCg6UKCBbA==";
      };
    };
    "@jridgewell/remapping-2.3.5" = {
      name = "_at_jridgewell_slash_remapping";
      packageName = "@jridgewell/remapping";
      version = "2.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/remapping/-/remapping-2.3.5.tgz";
        sha512 = "LI9u/+laYG4Ds1TDKSJW2YPrIlcVYOwi2fUC6xB43lueCjgxV4lffOCZCtYFiH6TNOX+tQKXx97T4IKHbhyHEQ==";
      };
    };
    "@jridgewell/resolve-uri-3.1.2" = {
      name = "_at_jridgewell_slash_resolve-uri";
      packageName = "@jridgewell/resolve-uri";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/resolve-uri/-/resolve-uri-3.1.2.tgz";
        sha512 = "bRISgCIjP20/tbWSPWMEi54QVPRZExkuD9lJL+UIxUKtwVJA8wW1Trb1jMs1RFXo1CBTNZ/5hpC9QvmKWdopKw==";
      };
    };
    "@jridgewell/sourcemap-codec-1.5.5" = {
      name = "_at_jridgewell_slash_sourcemap-codec";
      packageName = "@jridgewell/sourcemap-codec";
      version = "1.5.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/sourcemap-codec/-/sourcemap-codec-1.5.5.tgz";
        sha512 = "cYQ9310grqxueWbl+WuIUIaiUaDcj7WOq5fVhEljNVgRfOUhY9fy2zTvfoqWsnebh8Sl70VScFbICvJnLKB0Og==";
      };
    };
    "@jridgewell/trace-mapping-0.3.31" = {
      name = "_at_jridgewell_slash_trace-mapping";
      packageName = "@jridgewell/trace-mapping";
      version = "0.3.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/trace-mapping/-/trace-mapping-0.3.31.tgz";
        sha512 = "zzNR+SdQSDJzc8joaeP8QQoCQr8NuYx2dIIytl1QeBEZHJ9uW6hebsrYgbz8hJwUQao3TWCMtmfV8Nu1twOLAw==";
      };
    };
    "@luxass/strip-json-comments-1.4.0" = {
      name = "_at_luxass_slash_strip-json-comments";
      packageName = "@luxass/strip-json-comments";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@luxass/strip-json-comments/-/strip-json-comments-1.4.0.tgz";
        sha512 = "Zl343to4u/t8jz1q7R/1UY6hLX+344cwPLEXsIYthVwdU5zyjuVBGcpf2E24+QZkwFfRfmnHTcscreQzWn3hiA==";
      };
    };
    "@marko/compiler-5.39.40" = {
      name = "_at_marko_slash_compiler";
      packageName = "@marko/compiler";
      version = "5.39.40";
      src = fetchurl {
        url = "https://registry.npmjs.org/@marko/compiler/-/compiler-5.39.40.tgz";
        sha512 = "gQSdfJ5XOy01DtP7ULiqI1onp7Cix1QvnjM0KbfR2HMrWNI14V8V/2JguFAm3BzKEMZmmgvRLk0rvBzSm9FP6Q==";
      };
    };
    "@oxc-project/types-0.74.0" = {
      name = "_at_oxc-project_slash_types";
      packageName = "@oxc-project/types";
      version = "0.74.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@oxc-project/types/-/types-0.74.0.tgz";
        sha512 = "KOw/RZrVlHGhCXh1RufBFF7Nuo7HdY5w1lRJukM/igIl6x9qtz8QycDvZdzb4qnHO7znrPyo2sJrFJK2eKHgfQ==";
      };
    };
    "@prettier/plugin-hermes-0.0.3" = {
      name = "_at_prettier_slash_plugin-hermes";
      packageName = "@prettier/plugin-hermes";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@prettier/plugin-hermes/-/plugin-hermes-0.0.3.tgz";
        sha512 = "ahQNCXlyL39xKT3hT5TSnbE4zGLEWTVlRbzDJmQdd+TRBAeunfDuqrL8JIlN/1ky9ZEUWZnT590/XRCFyxgc2w==";
      };
    };
    "@prettier/plugin-oxc-0.0.4" = {
      name = "_at_prettier_slash_plugin-oxc";
      packageName = "@prettier/plugin-oxc";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@prettier/plugin-oxc/-/plugin-oxc-0.0.4.tgz";
        sha512 = "UGXe+g/rSRbglL0FOJiar+a+nUrst7KaFmsg05wYbKiInGWP6eAj/f8A2Uobgo5KxEtb2X10zeflNH6RK2xeIQ==";
      };
    };
    "@prettier/plugin-pug-3.4.2" = {
      name = "_at_prettier_slash_plugin-pug";
      packageName = "@prettier/plugin-pug";
      version = "3.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@prettier/plugin-pug/-/plugin-pug-3.4.2.tgz";
        sha512 = "/VOVeIscKYlPpsZrjrRV+44ZftCEIJq9Z/zR8PtAz/EDv82TKscw3z+fhTVqRz68G1TqQ/5COMFUVfPwPBH90w==";
      };
    };
    "@shopify/liquid-html-parser-2.9.0" = {
      name = "_at_shopify_slash_liquid-html-parser";
      packageName = "@shopify/liquid-html-parser";
      version = "2.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@shopify/liquid-html-parser/-/liquid-html-parser-2.9.0.tgz";
        sha512 = "bkI4tLbU47YUxpgbMa9fgeJjFEMvRNEFL644Yk0ZKo5H1IRzU4pPyCQ6PkGvb0JJnt7OZ+RDGvb6ZLCnAR2Z/A==";
      };
    };
    "@shopify/prettier-plugin-liquid-1.10.0" = {
      name = "_at_shopify_slash_prettier-plugin-liquid";
      packageName = "@shopify/prettier-plugin-liquid";
      version = "1.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@shopify/prettier-plugin-liquid/-/prettier-plugin-liquid-1.10.0.tgz";
        sha512 = "csHYjwuT34o8ja6EY0dUBYQS5UVwsKwRYxGiuG816Ov0B8lVd8FUjOwWUk2SnrNx3cGgL0no7z+Byapp7sC1Uw==";
      };
    };
    "@sveltejs/acorn-typescript-1.0.6" = {
      name = "_at_sveltejs_slash_acorn-typescript";
      packageName = "@sveltejs/acorn-typescript";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sveltejs/acorn-typescript/-/acorn-typescript-1.0.6.tgz";
        sha512 = "4awhxtMh4cx9blePWl10HRHj8Iivtqj+2QdDCSMDzxG+XKa9+VCNupQuCuvzEhYPzZSrX+0gC+0lHA/0fFKKQQ==";
      };
    };
    "@trivago/prettier-plugin-sort-imports-5.2.2" = {
      name = "_at_trivago_slash_prettier-plugin-sort-imports";
      packageName = "@trivago/prettier-plugin-sort-imports";
      version = "5.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@trivago/prettier-plugin-sort-imports/-/prettier-plugin-sort-imports-5.2.2.tgz";
        sha512 = "fYDQA9e6yTNmA13TLVSA+WMQRc5Bn/c0EUBditUHNfMMxN7M82c38b1kEggVE3pLpZ0FwkwJkUEKMiOi52JXFA==";
      };
    };
    "@types/debug-4.1.12" = {
      name = "_at_types_slash_debug";
      packageName = "@types/debug";
      version = "4.1.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/debug/-/debug-4.1.12.tgz";
        sha512 = "vIChWdVG3LG1SMxEvI/AK+FWJthlrqlTu7fbrlywTkkaONwk/UAGaULXRlf8vkzFBLVm0zkMdCquhL5aOjhXPQ==";
      };
    };
    "@types/estree-1.0.8" = {
      name = "_at_types_slash_estree";
      packageName = "@types/estree";
      version = "1.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/estree/-/estree-1.0.8.tgz";
        sha512 = "dWHzHa2WqEXI/O1E9OjrocMTKJl2mSrEolh1Iomrv6U+JuNwaHXsXx9bLu5gG7BUWFIN0skIQJQ/L1rIex4X6w==";
      };
    };
    "@types/luxon-3.7.1" = {
      name = "_at_types_slash_luxon";
      packageName = "@types/luxon";
      version = "3.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/luxon/-/luxon-3.7.1.tgz";
        sha512 = "H3iskjFIAn5SlJU7OuxUmTEpebK6TKB8rxZShDslBMZJ5u9S//KM1sbdAisiSrqwLQncVjnpi2OK2J51h+4lsg==";
      };
    };
    "@types/mdast-4.0.4" = {
      name = "_at_types_slash_mdast";
      packageName = "@types/mdast";
      version = "4.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/mdast/-/mdast-4.0.4.tgz";
        sha512 = "kGaNbPh1k7AFzgpud/gMdvIm5xuECykRR+JnWKQno9TAXVa6WIVCGTPvYGekIDL4uwCZQSYbUxNBSb1aUo79oA==";
      };
    };
    "@types/ms-2.1.0" = {
      name = "_at_types_slash_ms";
      packageName = "@types/ms";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/ms/-/ms-2.1.0.tgz";
        sha512 = "GsCCIZDE/p3i96vtEqx+7dBUGXrc7zeSK3wwPHIaRThS+9OhWIXRqzs4d6k1SVU8g91DrNRWxWUGhp5KXQb2VA==";
      };
    };
    "@types/unist-3.0.3" = {
      name = "_at_types_slash_unist";
      packageName = "@types/unist";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/unist/-/unist-3.0.3.tgz";
        sha512 = "ko/gIFJRv177XgZsZcBwnqJN5x/Gien8qNOn0D5bQU/zAzVf9Zt3BlcUiLqhV9y4ARk0GbT3tnUiPNgnTXzc/Q==";
      };
    };
    "@volar/language-core-2.4.23" = {
      name = "_at_volar_slash_language-core";
      packageName = "@volar/language-core";
      version = "2.4.23";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/language-core/-/language-core-2.4.23.tgz";
        sha512 = "hEEd5ET/oSmBC6pi1j6NaNYRWoAiDhINbT8rmwtINugR39loROSlufGdYMF9TaKGfz+ViGs1Idi3mAhnuPcoGQ==";
      };
    };
    "@volar/source-map-2.4.23" = {
      name = "_at_volar_slash_source-map";
      packageName = "@volar/source-map";
      version = "2.4.23";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/source-map/-/source-map-2.4.23.tgz";
        sha512 = "Z1Uc8IB57Lm6k7q6KIDu/p+JWtf3xsXJqAX/5r18hYOTpJyBn0KXUR8oTJ4WFYOcDzWC9n3IflGgHowx6U6z9Q==";
      };
    };
    "@volar/typescript-2.4.23" = {
      name = "_at_volar_slash_typescript";
      packageName = "@volar/typescript";
      version = "2.4.23";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/typescript/-/typescript-2.4.23.tgz";
        sha512 = "lAB5zJghWxVPqfcStmAP1ZqQacMpe90UrP5RJ3arDyrhy4aCUQqmxPPLB2PWDKugvylmO41ljK7vZ+t6INMTag==";
      };
    };
    "@vue/compiler-core-3.5.22" = {
      name = "_at_vue_slash_compiler-core";
      packageName = "@vue/compiler-core";
      version = "3.5.22";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/compiler-core/-/compiler-core-3.5.22.tgz";
        sha512 = "jQ0pFPmZwTEiRNSb+i9Ow/I/cHv2tXYqsnHKKyCQ08irI2kdF5qmYedmF8si8mA7zepUFmJ2hqzS8CQmNOWOkQ==";
      };
    };
    "@vue/compiler-dom-3.5.22" = {
      name = "_at_vue_slash_compiler-dom";
      packageName = "@vue/compiler-dom";
      version = "3.5.22";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/compiler-dom/-/compiler-dom-3.5.22.tgz";
        sha512 = "W8RknzUM1BLkypvdz10OVsGxnMAuSIZs9Wdx1vzA3mL5fNMN15rhrSCLiTm6blWeACwUwizzPVqGJgOGBEN/hA==";
      };
    };
    "@vue/compiler-sfc-3.5.22" = {
      name = "_at_vue_slash_compiler-sfc";
      packageName = "@vue/compiler-sfc";
      version = "3.5.22";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/compiler-sfc/-/compiler-sfc-3.5.22.tgz";
        sha512 = "tbTR1zKGce4Lj+JLzFXDq36K4vcSZbJ1RBu8FxcDv1IGRz//Dh2EBqksyGVypz3kXpshIfWKGOCcqpSbyGWRJQ==";
      };
    };
    "@vue/compiler-ssr-3.5.22" = {
      name = "_at_vue_slash_compiler-ssr";
      packageName = "@vue/compiler-ssr";
      version = "3.5.22";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/compiler-ssr/-/compiler-ssr-3.5.22.tgz";
        sha512 = "GdgyLvg4R+7T8Nk2Mlighx7XGxq/fJf9jaVofc3IL0EPesTE86cP/8DD1lT3h1JeZr2ySBvyqKQJgbS54IX1Ww==";
      };
    };
    "@vue/language-core-3.1.1" = {
      name = "_at_vue_slash_language-core";
      packageName = "@vue/language-core";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/language-core/-/language-core-3.1.1.tgz";
        sha512 = "qjMY3Q+hUCjdH+jLrQapqgpsJ0rd/2mAY02lZoHG3VFJZZZKLjAlV+Oo9QmWIT4jh8+Rx8RUGUi++d7T9Wb6Mw==";
      };
    };
    "@vue/shared-3.5.22" = {
      name = "_at_vue_slash_shared";
      packageName = "@vue/shared";
      version = "3.5.22";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/shared/-/shared-3.5.22.tgz";
        sha512 = "F4yc6palwq3TT0u+FYf0Ns4Tfl9GRFURDN2gWG7L1ecIaS/4fCIuFOjMTnCyjsu/OK6vaDKLCrGAa+KvvH+h4w==";
      };
    };
    "@zackad/prettier-plugin-twig-0.16.0" = {
      name = "_at_zackad_slash_prettier-plugin-twig";
      packageName = "@zackad/prettier-plugin-twig";
      version = "0.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@zackad/prettier-plugin-twig/-/prettier-plugin-twig-0.16.0.tgz";
        sha512 = "04ra6HWYHA5kuiv3def2d6MHzCyzG9zuCYWB5jvVpOqDrMJEt2I5D+xsQa4MtvkJ5v89kq0uFFT/PBd772bh/Q==";
      };
    };
    "acorn-7.4.1" = {
      name = "acorn";
      packageName = "acorn";
      version = "7.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-7.4.1.tgz";
        sha512 = "nQyp0o1/mNdbTO1PO6kHkwSrmgZ0MT/jCCpNiwbUjGoRN4dlBhqJtoQuCnEOKzgTVwg0ZWiCoQy6SxMebQVh8A==";
      };
    };
    "acorn-8.15.0" = {
      name = "acorn";
      packageName = "acorn";
      version = "8.15.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-8.15.0.tgz";
        sha512 = "NZyJarBfL7nWwIq+FDL6Zp/yHEhePMNnnJ0y3qfieCrmNvYct8uvtiV41UvlSe6apAfk0fY1FbWx+NwfmpvtTg==";
      };
    };
    "alien-signals-3.0.3" = {
      name = "alien-signals";
      packageName = "alien-signals";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/alien-signals/-/alien-signals-3.0.3.tgz";
        sha512 = "2JXjom6R7ZwrISpUphLhf4htUq1aKRCennTJ6u9kFfr3sLmC9+I4CxxVi+McoFnIg+p1HnVrfLT/iCt4Dlz//Q==";
      };
    };
    "ansi-styles-6.2.3" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "6.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-6.2.3.tgz";
        sha512 = "4Dj6M28JB+oAH8kFkTLUo+a2jwOFkuqb3yucU0CANcRRUbxS0cP0nZYCGjcc3BNXwRIsUVmDGgzawme7zvJHvg==";
      };
    };
    "aria-query-5.3.2" = {
      name = "aria-query";
      packageName = "aria-query";
      version = "5.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/aria-query/-/aria-query-5.3.2.tgz";
        sha512 = "COROpnaoap1E2F000S62r6A60uHZnmlvomhfyT2DlTcrY1OrBKn2UhH7qn5wTC9zMvD0AY7csdPSNwKP+7WiQw==";
      };
    };
    "async-function-1.0.0" = {
      name = "async-function";
      packageName = "async-function";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/async-function/-/async-function-1.0.0.tgz";
        sha512 = "hsU18Ae8CDTR6Kgu9DYf0EbCr/a5iGL0rytQDobUcdpYOKokk8LEjVphnXkDkgpi0wYVsqrXuP0bZxJaTqdgoA==";
      };
    };
    "async-generator-function-1.0.0" = {
      name = "async-generator-function";
      packageName = "async-generator-function";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/async-generator-function/-/async-generator-function-1.0.0.tgz";
        sha512 = "+NAXNqgCrB95ya4Sr66i1CL2hqLVckAk7xwRYWdcm39/ELQ6YNn1aw5r0bdQtqNZgQpEWzc5yc/igXc7aL5SLA==";
      };
    };
    "axobject-query-4.1.0" = {
      name = "axobject-query";
      packageName = "axobject-query";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/axobject-query/-/axobject-query-4.1.0.tgz";
        sha512 = "qIj0G9wZbMGNLjLmg1PT6v2mE9AH2zlnADJD/2tC6E00hgmhUOfEB6greHPAfLRSufHqROIUTkw6E+M3lH0PTQ==";
      };
    };
    "baseline-browser-mapping-2.8.19" = {
      name = "baseline-browser-mapping";
      packageName = "baseline-browser-mapping";
      version = "2.8.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/baseline-browser-mapping/-/baseline-browser-mapping-2.8.19.tgz";
        sha512 = "zoKGUdu6vb2jd3YOq0nnhEDQVbPcHhco3UImJrv5dSkvxTc2pl2WjOPsjZXDwPDSl5eghIMuY3R6J9NDKF3KcQ==";
      };
    };
    "binary-searching-2.0.5" = {
      name = "binary-searching";
      packageName = "binary-searching";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/binary-searching/-/binary-searching-2.0.5.tgz";
        sha512 = "v4N2l3RxL+m4zDxyxz3Ne2aTmiPn8ZUpKFpdPtO+ItW1NcTCXA7JeHG5GMBSvoKSkQZ9ycS+EouDVxYB9ufKWA==";
      };
    };
    "browser-or-node-3.0.0" = {
      name = "browser-or-node";
      packageName = "browser-or-node";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/browser-or-node/-/browser-or-node-3.0.0.tgz";
        sha512 = "iczIdVJzGEYhP5DqQxYM9Hh7Ztpqqi+CXZpSmX8ALFs9ecXkQIeqRyM6TfxEfMVpwhl3dSuDvxdzzo9sUOIVBQ==";
      };
    };
    "browserslist-4.27.0" = {
      name = "browserslist";
      packageName = "browserslist";
      version = "4.27.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserslist/-/browserslist-4.27.0.tgz";
        sha512 = "AXVQwdhot1eqLihwasPElhX2tAZiBjWdJ9i/Zcj2S6QYIjkx62OKSfnobkriB81C3l4w0rVy3Nt4jaTBltYEpw==";
      };
    };
    "buffer-from-1.1.2" = {
      name = "buffer-from";
      packageName = "buffer-from";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-from/-/buffer-from-1.1.2.tgz";
        sha512 = "E+XQCRwSbaaiChtv6k6Dwgc+bx+Bs6vuKJHHl5kox/BaKbhiXzqQOwK4cO22yElGp2OCmjwVhT3HmxgyPGnJfQ==";
      };
    };
    "call-bind-apply-helpers-1.0.2" = {
      name = "call-bind-apply-helpers";
      packageName = "call-bind-apply-helpers";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/call-bind-apply-helpers/-/call-bind-apply-helpers-1.0.2.tgz";
        sha512 = "Sp1ablJ0ivDkSzjcaJdxEunN5/XvksFJ2sMBFfq6x0ryhQV/2b/KwFe21cMpmHtPOSij8K99/wSfoEuTObmuMQ==";
      };
    };
    "call-bound-1.0.4" = {
      name = "call-bound";
      packageName = "call-bound";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/call-bound/-/call-bound-1.0.4.tgz";
        sha512 = "+ys997U96po4Kx/ABpBCqhA9EuxJaQWDQg7295H4hBphv3IZg0boBKuwYpt4YXp6MZ5AmZQnU/tyMTlRpaSejg==";
      };
    };
    "caniuse-lite-1.0.30001751" = {
      name = "caniuse-lite";
      packageName = "caniuse-lite";
      version = "1.0.30001751";
      src = fetchurl {
        url = "https://registry.npmjs.org/caniuse-lite/-/caniuse-lite-1.0.30001751.tgz";
        sha512 = "A0QJhug0Ly64Ii3eIqHu5X51ebln3k4yTUkY1j8drqpWHVreg/VLijN48cZ1bYPiqOQuqpkIKnzr/Ul8V+p6Cw==";
      };
    };
    "character-entities-2.0.2" = {
      name = "character-entities";
      packageName = "character-entities";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/character-entities/-/character-entities-2.0.2.tgz";
        sha512 = "shx7oQ0Awen/BRIdkjkvz54PnEEI/EjwXDSIZp86/KKdbafHh1Df/RYGBhn4hbe2+uKC9FnT5UCEdyPz3ai9hQ==";
      };
    };
    "character-parser-2.2.0" = {
      name = "character-parser";
      packageName = "character-parser";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/character-parser/-/character-parser-2.2.0.tgz";
        sha512 = "+UqJQjFEFaTAs3bNsF2j2kEN1baG/zghZbdqoYEDxGZtJo9LBzl1A+m0D4n3qKx8N2FNv8/Xp6yV9mQmBuptaw==";
      };
    };
    "clsx-2.1.1" = {
      name = "clsx";
      packageName = "clsx";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/clsx/-/clsx-2.1.1.tgz";
        sha512 = "eYm0QWBtUrBWZWG0d386OGAw16Z995PiOVo2B7bjWSbHedGl5e0ZWaq65kOGgUSNesEIDkB9ISbTg/JK9dhCZA==";
      };
    };
    "comment-parser-1.4.1" = {
      name = "comment-parser";
      packageName = "comment-parser";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/comment-parser/-/comment-parser-1.4.1.tgz";
        sha512 = "buhp5kePrmda3vhc5B9t7pUQXAb2Tnd0qgpkIhPhkHXxJpiPJ11H0ZEU0oBpJ2QztSbzG/ZxMj/CHsYJqRHmyg==";
      };
    };
    "complain-1.6.1" = {
      name = "complain";
      packageName = "complain";
      version = "1.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/complain/-/complain-1.6.1.tgz";
        sha512 = "WsiVAbAPcPSwyC5k8g/PLceaW0MXJUw61KqBd9uiyDOSuDIC6Ho/EbyhdFjeV6wq44R2g/b8IFpvV/1ZyXiqUQ==";
      };
    };
    "content-tag-4.0.0" = {
      name = "content-tag";
      packageName = "content-tag";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-tag/-/content-tag-4.0.0.tgz";
        sha512 = "qqJiY9nueYAI396MOmfOk+w/0KL6ERKxANQcSKcR0CrNTc38yT//b73l+WHr9brZx57bFHNaW7a/6Yll0bn95w==";
      };
    };
    "convert-source-map-2.0.0" = {
      name = "convert-source-map";
      packageName = "convert-source-map";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/convert-source-map/-/convert-source-map-2.0.0.tgz";
        sha512 = "Kvp459HrV2FEJ1CAsi1Ku+MY3kasH19TFykTz2xWmMeq6bk2NU3XXvfJ+Q61m0xktWwt+1HSYf3JZsTms3aRJg==";
      };
    };
    "css-declaration-sorter-7.3.0" = {
      name = "css-declaration-sorter";
      packageName = "css-declaration-sorter";
      version = "7.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-declaration-sorter/-/css-declaration-sorter-7.3.0.tgz";
        sha512 = "LQF6N/3vkAMYF4xoHLJfG718HRJh34Z8BnNhd6bosOMIVjMlhuZK5++oZa3uYAgrI5+7x2o27gUqTR2U/KjUOQ==";
      };
    };
    "debug-4.4.3" = {
      name = "debug";
      packageName = "debug";
      version = "4.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.4.3.tgz";
        sha512 = "RGwwWnwQvkVfavKVt22FGLw+xYSdzARwm0ru6DhTVA3umU5hZc28V3kO4stgYryrTlLpuvgI9GiijltAjNbcqA==";
      };
    };
    "decode-named-character-reference-1.2.0" = {
      name = "decode-named-character-reference";
      packageName = "decode-named-character-reference";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decode-named-character-reference/-/decode-named-character-reference-1.2.0.tgz";
        sha512 = "c6fcElNV6ShtZXmsgNgFFV5tVX2PaV4g+MOAkb8eXHvn6sryJBrZa9r0zV6+dtTyoCKxtDy5tyQ5ZwQuidtd+Q==";
      };
    };
    "deep-eql-5.0.2" = {
      name = "deep-eql";
      packageName = "deep-eql";
      version = "5.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-eql/-/deep-eql-5.0.2.tgz";
        sha512 = "h5k/5U50IJJFpzfL6nO9jaaumfjO/f2NjK/oYB2Djzm4p9L+3T9qWpZqZ2hAbLPuuYq9wrU08WQyBTL5GbPk5Q==";
      };
    };
    "deepcopy-esm-2.1.1" = {
      name = "deepcopy-esm";
      packageName = "deepcopy-esm";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/deepcopy-esm/-/deepcopy-esm-2.1.1.tgz";
        sha512 = "0lopQd/gi3excE3sgBrjuR3gJv6ZElk027i30pUgdjtvSJl/OoZ8B6L42GUBm6C3G8hD1EB5ir2gTYnINzWx4g==";
      };
    };
    "dequal-2.0.3" = {
      name = "dequal";
      packageName = "dequal";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/dequal/-/dequal-2.0.3.tgz";
        sha512 = "0je+qPKHEMohvfRTCEo3CrPG6cAzAYgmzKyxRiYSSDkS6eGJdyVJm7WaYA5ECaAD9wLB2T4EEeymA5aFVcYXCA==";
      };
    };
    "devlop-1.1.0" = {
      name = "devlop";
      packageName = "devlop";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/devlop/-/devlop-1.1.0.tgz";
        sha512 = "RWmIqhcFf1lRYBvNmr7qTNuyCt/7/ns2jbpp1+PalgE/rDQcBT0fioSMUpJ93irlUhC5hrg4cYqe6U+0ImW0rA==";
      };
    };
    "diff-8.0.2" = {
      name = "diff";
      packageName = "diff";
      version = "8.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/diff/-/diff-8.0.2.tgz";
        sha512 = "sSuxWU5j5SR9QQji/o2qMvqRNYRDOcBTgsJ/DeCf4iSN4gW+gNMXM7wFIP+fdXZxoNiAnHUTGjCr+TSWXdRDKg==";
      };
    };
    "dunder-proto-1.0.1" = {
      name = "dunder-proto";
      packageName = "dunder-proto";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dunder-proto/-/dunder-proto-1.0.1.tgz";
        sha512 = "KIN/nDJBQRcXw0MLVhZE9iQHmG68qAVIBg9CqmUYjmQIhgij9U5MFvrqkUL5FbtyyzZuOeOt0zdeRe4UY7ct+A==";
      };
    };
    "electron-to-chromium-1.5.238" = {
      name = "electron-to-chromium";
      packageName = "electron-to-chromium";
      version = "1.5.238";
      src = fetchurl {
        url = "https://registry.npmjs.org/electron-to-chromium/-/electron-to-chromium-1.5.238.tgz";
        sha512 = "khBdc+w/Gv+cS8e/Pbnaw/FXcBUeKrRVik9IxfXtgREOWyJhR4tj43n3amkVogJ/yeQUqzkrZcFhtIxIdqmmcQ==";
      };
    };
    "entities-4.5.0" = {
      name = "entities";
      packageName = "entities";
      version = "4.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-4.5.0.tgz";
        sha512 = "V0hjH4dGPh9Ao5p0MoRY6BVqtwCjhz6vI5LT8AJ55H+4g9/4vbHx1I54fS0XuclLhDHArPQCiMjDxjaL8fPxhw==";
      };
    };
    "error-stack-parser-2.1.4" = {
      name = "error-stack-parser";
      packageName = "error-stack-parser";
      version = "2.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/error-stack-parser/-/error-stack-parser-2.1.4.tgz";
        sha512 = "Sk5V6wVazPhq5MhpO+AUxJn5x7XSXGl1R93Vn7i+zS15KDVxQijejNCrz8340/2bgLBjR9GtEG8ZVKONDjcqGQ==";
      };
    };
    "es-define-property-1.0.1" = {
      name = "es-define-property";
      packageName = "es-define-property";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-define-property/-/es-define-property-1.0.1.tgz";
        sha512 = "e3nRfgfUZ4rNGL232gUgX06QNyyez04KdjFrF+LTRoOXmrOgFKDg4BCdsjW8EnT69eqdYGmRpJwiPVYNrCaW3g==";
      };
    };
    "es-errors-1.3.0" = {
      name = "es-errors";
      packageName = "es-errors";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-errors/-/es-errors-1.3.0.tgz";
        sha512 = "Zf5H2Kxt2xjTvbJvP2ZWLEICxA6j+hAmMzIlypy4xcBg1vKVnx89Wy0GbS+kf5cwCVFFzdCFh2XSCFNULS6csw==";
      };
    };
    "es-object-atoms-1.1.1" = {
      name = "es-object-atoms";
      packageName = "es-object-atoms";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-object-atoms/-/es-object-atoms-1.1.1.tgz";
        sha512 = "FGgH2h8zKNim9ljj7dankFPcICIK9Cp5bm+c2gQSYePhpaG5+esrLODihIorn+Pe6FGJzWhXQotPv73jTaldXA==";
      };
    };
    "escalade-3.2.0" = {
      name = "escalade";
      packageName = "escalade";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/escalade/-/escalade-3.2.0.tgz";
        sha512 = "WUj2qlxaQtO4g6Pq5c29GTcWGDyd8itL8zTlipgECz3JesAiiOKotd8JU6otB3PACgG6xkJUyVhboMS+bje/jA==";
      };
    };
    "esm-env-1.2.2" = {
      name = "esm-env";
      packageName = "esm-env";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/esm-env/-/esm-env-1.2.2.tgz";
        sha512 = "Epxrv+Nr/CaL4ZcFGPJIYLWFom+YeV1DqMLHJoEd9SYRxNbaFruBwfEX/kkHUJf55j2+TUbmDcmuilbP1TmXHA==";
      };
    };
    "esrap-2.1.0" = {
      name = "esrap";
      packageName = "esrap";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/esrap/-/esrap-2.1.0.tgz";
        sha512 = "yzmPNpl7TBbMRC5Lj2JlJZNPml0tzqoqP5B1JXycNUwtqma9AKCO0M2wHrdgsHcy1WRW7S9rJknAMtByg3usgA==";
      };
    };
    "estree-walker-2.0.2" = {
      name = "estree-walker";
      packageName = "estree-walker";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/estree-walker/-/estree-walker-2.0.2.tgz";
        sha512 = "Rfkk/Mp/DL7JVje3u18FxFujQlTNR2q6QfMSMB7AvCBx91NGj/ba3kCfza0f6dVDbw7YlRf/nDrn7pQrCCyQ/w==";
      };
    };
    "expect-type-1.2.2" = {
      name = "expect-type";
      packageName = "expect-type";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/expect-type/-/expect-type-1.2.2.tgz";
        sha512 = "JhFGDVJ7tmDJItKhYgJCGLOWjuK9vPxiXoUFLwLDc99NlmklilbiQJwoctZtt13+xMw91MCk/REan6MWHqDjyA==";
      };
    };
    "function-bind-1.1.2" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.2.tgz";
        sha512 = "7XHNxH7qX9xG5mIwxkhumTox/MIRNcOgDrxWsMt2pAr23WHp6MrRlN7FBSFpCpr+oVO0F744iUgR82nJMfG2SA==";
      };
    };
    "generator-function-2.0.1" = {
      name = "generator-function";
      packageName = "generator-function";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/generator-function/-/generator-function-2.0.1.tgz";
        sha512 = "SFdFmIJi+ybC0vjlHN0ZGVGHc3lgE0DxPAT0djjVg+kjOnSqclqmj0KQ7ykTOLP6YxoqOvuAODGdcHJn+43q3g==";
      };
    };
    "gensync-1.0.0-beta.2" = {
      name = "gensync";
      packageName = "gensync";
      version = "1.0.0-beta.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/gensync/-/gensync-1.0.0-beta.2.tgz";
        sha512 = "3hN7NaskYvMDLQY55gnW3NQ+mesEAepTqlg+VEbj7zzqEMBVNhzcGYYeqFo/TlYz6eQiFcp1HcsCZO+nGgS8zg==";
      };
    };
    "get-intrinsic-1.3.1" = {
      name = "get-intrinsic";
      packageName = "get-intrinsic";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-intrinsic/-/get-intrinsic-1.3.1.tgz";
        sha512 = "fk1ZVEeOX9hVZ6QzoBNEC55+Ucqg4sTVwrVuigZhuRPESVFpMyXnd3sbXvPOwp7Y9riVyANiqhEuRF0G1aVSeQ==";
      };
    };
    "get-proto-1.0.1" = {
      name = "get-proto";
      packageName = "get-proto";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-proto/-/get-proto-1.0.1.tgz";
        sha512 = "sTSfBjoXBp89JvIKIefqw7U2CCebsc74kiY6awiGogKtoSGbgjYE/G/+l9sF3MWFPNc9IcoOC4ODfKHfxFmp0g==";
      };
    };
    "gopd-1.2.0" = {
      name = "gopd";
      packageName = "gopd";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/gopd/-/gopd-1.2.0.tgz";
        sha512 = "ZUKRh6/kUFoAiTAtTYPZJ3hw9wNxx+BIBOijnlG9PnrJsCcSjs1wyyD6vJpaYtgnzDrKYRSqf3OO6Rfa93xsRg==";
      };
    };
    "has-symbols-1.1.0" = {
      name = "has-symbols";
      packageName = "has-symbols";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-symbols/-/has-symbols-1.1.0.tgz";
        sha512 = "1cDNdwJ2Jaohmb3sg4OmKaMBwuC48sYni5HUw2DvsC8LjGTLK9h+eb1X6RyuOHe4hT0ULCW68iomhjUoKUqlPQ==";
      };
    };
    "has-tostringtag-1.0.2" = {
      name = "has-tostringtag";
      packageName = "has-tostringtag";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-tostringtag/-/has-tostringtag-1.0.2.tgz";
        sha512 = "NqADB8VjPFLM2V0VvHUewwwsw0ZWBaIdgo+ieHtK3hasLz4qeCRjYcqfB6AQrBggRKppKF8L52/VqdVsO47Dlw==";
      };
    };
    "hasown-2.0.2" = {
      name = "hasown";
      packageName = "hasown";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/hasown/-/hasown-2.0.2.tgz";
        sha512 = "0hJU9SCPvmMzIBdZFqNPXWa6dqh7WdH0cII9y+CyS8rG3nL48Bclra9HmKhVVUHyPWNH5Y7xDwAB7bfgSjkUMQ==";
      };
    };
    "he-1.2.0" = {
      name = "he";
      packageName = "he";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/he/-/he-1.2.0.tgz";
        sha512 = "F/1DnUGPopORZi0ni+CvrCgHQ5FyEAHRLSApuYWMmrbSwoN2Mn/7k+Gl38gJnR7yyDZk6WLXwiGod1JOWNDKGw==";
      };
    };
    "html-styles-1.0.0" = {
      name = "html-styles";
      packageName = "html-styles";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/html-styles/-/html-styles-1.0.0.tgz";
        sha512 = "cDl5dcj73oI4Hy0DSUNh54CAwslNLJRCCoO+RNkVo+sBrjA/0+7E/xzvj3zH/GxbbBLGJhE0hBe1eg+0FINC6w==";
      };
    };
    "htmljs-parser-5.7.4" = {
      name = "htmljs-parser";
      packageName = "htmljs-parser";
      version = "5.7.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/htmljs-parser/-/htmljs-parser-5.7.4.tgz";
        sha512 = "PCGI7/Z10oBkpKKqbQ9Wgd0GZjSQ/dV7QlBjOmaqD1FkBsHWk730BW9mJCbnXfRbtZCdLh8M8IA8YeKPu9tGaQ==";
      };
    };
    "is-expression-4.0.0" = {
      name = "is-expression";
      packageName = "is-expression";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-expression/-/is-expression-4.0.0.tgz";
        sha512 = "zMIXX63sxzG3XrkHkrAPvm/OVZVSCPNkwMHU8oTX7/U3AL78I0QXCEICXUM13BIa8TYGZ68PiTKfQz3yaTNr4A==";
      };
    };
    "is-reference-3.0.3" = {
      name = "is-reference";
      packageName = "is-reference";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-reference/-/is-reference-3.0.3.tgz";
        sha512 = "ixkJoqQvAP88E6wLydLGGqCJsrFUnqoH6HnaczB8XmDH1oaWU+xxdptvikTgaEhtZ53Ky6YXiBuUI2WXLMCwjw==";
      };
    };
    "is-regex-1.2.1" = {
      name = "is-regex";
      packageName = "is-regex";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-regex/-/is-regex-1.2.1.tgz";
        sha512 = "MjYsKHO5O7mCsmRGxWcLWheFqN9DJ/2TmngvjKXihe6efViPqc274+Fx/4fYj/r03+ESvBdTXK0V6tA3rgez1g==";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha512 = "VLghIWNM6ELQzo7zwmcg0NmTVyWKYjvIeM83yjp0wRDTmUnrM678fQbcKBo6n2CJEF0szoG//ytg+TKla89ALQ==";
      };
    };
    "isobject-2.1.0" = {
      name = "isobject";
      packageName = "isobject";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isobject/-/isobject-2.1.0.tgz";
        sha512 = "+OUdGJlgjOBZDfxnDjYYG6zp487z0JGNQq3cYQYg5f5hKR+syHMsaztzGeml/4kGG55CSpKSpWTY+jYGgsHLgA==";
      };
    };
    "javascript-natural-sort-0.7.1" = {
      name = "javascript-natural-sort";
      packageName = "javascript-natural-sort";
      version = "0.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/javascript-natural-sort/-/javascript-natural-sort-0.7.1.tgz";
        sha512 = "nO6jcEfZWQXDhOiBtG2KvKyEptz7RVbpGP4vTD2hLBdmNQSsCiicO2Ioinv6UI4y9ukqnBpy+XZ9H6uLNgJTlw==";
      };
    };
    "js-tokens-4.0.0" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz";
        sha512 = "RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==";
      };
    };
    "jsesc-3.1.0" = {
      name = "jsesc";
      packageName = "jsesc";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsesc/-/jsesc-3.1.0.tgz";
        sha512 = "/sM3dO2FOzXjKQhJuo0Q173wf2KOo8t4I8vHy6lF9poUp7bKT0/NHE8fPX23PwfhnykfqnC2xRxOnVw5XuGIaA==";
      };
    };
    "json5-2.2.3" = {
      name = "json5";
      packageName = "json5";
      version = "2.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/json5/-/json5-2.2.3.tgz";
        sha512 = "XmOWe7eyHYH14cLdVPoyg+GOH3rYX++KpzrylJwSW98t3Nk+U8XOl8FWKOgwtzdb8lXGf6zYwDUzeHMWfxasyg==";
      };
    };
    "kleur-4.1.5" = {
      name = "kleur";
      packageName = "kleur";
      version = "4.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/kleur/-/kleur-4.1.5.tgz";
        sha512 = "o+NO+8WrRiQEE4/7nwRJhN1HWpVmJm511pBHUxPLtp0BUISzlBplORYSmTclCnJvQq2tKu/sgl3xVpkc7ZWuQQ==";
      };
    };
    "lasso-caching-fs-1.0.2" = {
      name = "lasso-caching-fs";
      packageName = "lasso-caching-fs";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lasso-caching-fs/-/lasso-caching-fs-1.0.2.tgz";
        sha512 = "mudop0s8U3tLm3Fn9lhiZsiELpLeJToEo6RlDLdph7vWRxL9Sz0o+9WUw1IwlpCYXv/P0CLsMYWFgPwIKWEYvg==";
      };
    };
    "lasso-package-root-1.0.1" = {
      name = "lasso-package-root";
      packageName = "lasso-package-root";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lasso-package-root/-/lasso-package-root-1.0.1.tgz";
        sha512 = "j6LnauNCldqSDvOxoKpD6sTzudPGMiwcZQbySoF9KvJ0lD9Dp2t6QZF8kC0jbUDHuQPiAo5RuQ/mC3AGXscUYA==";
      };
    };
    "line-column-1.0.2" = {
      name = "line-column";
      packageName = "line-column";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/line-column/-/line-column-1.0.2.tgz";
        sha512 = "Ktrjk5noGYlHsVnYWh62FLVs4hTb8A3e+vucNZMgPeAOITdshMSgv4cCZQeRDjm7+goqmo6+liZwTXo+U3sVww==";
      };
    };
    "locate-character-3.0.0" = {
      name = "locate-character";
      packageName = "locate-character";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/locate-character/-/locate-character-3.0.0.tgz";
        sha512 = "SW13ws7BjaeJ6p7Q6CO2nchbYEc3X3J6WrmTTDto7yMPqVSZTUyY5Tjbid+Ab8gLnATtygYtiDIJGQRRn2ZOiA==";
      };
    };
    "lodash-4.17.21" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz";
        sha512 = "v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==";
      };
    };
    "lru-cache-5.1.1" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-5.1.1.tgz";
        sha512 = "KpNARQA3Iwv+jTA0utUVVbrh+Jlrr1Fv0e56GGzAFOXN7dk/FviaDW8LHmK52DlcH4WP2n6gI8vN1aesBFgo9w==";
      };
    };
    "luxon-3.7.2" = {
      name = "luxon";
      packageName = "luxon";
      version = "3.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/luxon/-/luxon-3.7.2.tgz";
        sha512 = "vtEhXh/gNjI9Yg1u4jX/0YVPMvxzHuGgCm6tC5kZyb08yjGWGnqAjGJvcXbqQR2P3MyMEFnRbpcdFS6PBcLqew==";
      };
    };
    "magic-string-0.30.19" = {
      name = "magic-string";
      packageName = "magic-string";
      version = "0.30.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/magic-string/-/magic-string-0.30.19.tgz";
        sha512 = "2N21sPY9Ws53PZvsEpVtNuSW+ScYbQdp4b9qUaL+9QkHUrGFKo56Lg9Emg5s9V/qrtNBmiR01sYhUOwu3H+VOw==";
      };
    };
    "math-intrinsics-1.1.0" = {
      name = "math-intrinsics";
      packageName = "math-intrinsics";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/math-intrinsics/-/math-intrinsics-1.1.0.tgz";
        sha512 = "/IXtbwEk5HTPyEwyKX6hGkYXxM9nbj64B+ilVJnC/R6B0pH5G4V3b0pVbL7DBj4tkhBAppbQUlf6F6Xl9LHu1g==";
      };
    };
    "mdast-util-from-markdown-2.0.2" = {
      name = "mdast-util-from-markdown";
      packageName = "mdast-util-from-markdown";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-util-from-markdown/-/mdast-util-from-markdown-2.0.2.tgz";
        sha512 = "uZhTV/8NBuw0WHkPTrCqDOl0zVe1BIng5ZtHoDk49ME1qqcjYmmLmOf0gELgcRMxN4w2iuIeVso5/6QymSrgmA==";
      };
    };
    "mdast-util-to-string-4.0.0" = {
      name = "mdast-util-to-string";
      packageName = "mdast-util-to-string";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-util-to-string/-/mdast-util-to-string-4.0.0.tgz";
        sha512 = "0H44vDimn51F0YwvxSJSm0eCDOJTRlmN0R1yBh4HLj9wiV1Dn0QoXGbvFAWj2hSItVTlCmBF1hqKlIyUBVFLPg==";
      };
    };
    "micromark-4.0.2" = {
      name = "micromark";
      packageName = "micromark";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark/-/micromark-4.0.2.tgz";
        sha512 = "zpe98Q6kvavpCr1NPVSCMebCKfD7CA2NqZ+rykeNhONIJBpc1tFKt9hucLGwha3jNTNI8lHpctWJWoimVF4PfA==";
      };
    };
    "micromark-core-commonmark-2.0.3" = {
      name = "micromark-core-commonmark";
      packageName = "micromark-core-commonmark";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-core-commonmark/-/micromark-core-commonmark-2.0.3.tgz";
        sha512 = "RDBrHEMSxVFLg6xvnXmb1Ayr2WzLAWjeSATAoxwKYJV94TeNavgoIdA0a9ytzDSVzBy2YKFK+emCPOEibLeCrg==";
      };
    };
    "micromark-factory-destination-2.0.1" = {
      name = "micromark-factory-destination";
      packageName = "micromark-factory-destination";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-factory-destination/-/micromark-factory-destination-2.0.1.tgz";
        sha512 = "Xe6rDdJlkmbFRExpTOmRj9N3MaWmbAgdpSrBQvCFqhezUn4AHqJHbaEnfbVYYiexVSs//tqOdY/DxhjdCiJnIA==";
      };
    };
    "micromark-factory-label-2.0.1" = {
      name = "micromark-factory-label";
      packageName = "micromark-factory-label";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-factory-label/-/micromark-factory-label-2.0.1.tgz";
        sha512 = "VFMekyQExqIW7xIChcXn4ok29YE3rnuyveW3wZQWWqF4Nv9Wk5rgJ99KzPvHjkmPXF93FXIbBp6YdW3t71/7Vg==";
      };
    };
    "micromark-factory-space-2.0.1" = {
      name = "micromark-factory-space";
      packageName = "micromark-factory-space";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-factory-space/-/micromark-factory-space-2.0.1.tgz";
        sha512 = "zRkxjtBxxLd2Sc0d+fbnEunsTj46SWXgXciZmHq0kDYGnck/ZSGj9/wULTV95uoeYiK5hRXP2mJ98Uo4cq/LQg==";
      };
    };
    "micromark-factory-title-2.0.1" = {
      name = "micromark-factory-title";
      packageName = "micromark-factory-title";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-factory-title/-/micromark-factory-title-2.0.1.tgz";
        sha512 = "5bZ+3CjhAd9eChYTHsjy6TGxpOFSKgKKJPJxr293jTbfry2KDoWkhBb6TcPVB4NmzaPhMs1Frm9AZH7OD4Cjzw==";
      };
    };
    "micromark-factory-whitespace-2.0.1" = {
      name = "micromark-factory-whitespace";
      packageName = "micromark-factory-whitespace";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-factory-whitespace/-/micromark-factory-whitespace-2.0.1.tgz";
        sha512 = "Ob0nuZ3PKt/n0hORHyvoD9uZhr+Za8sFoP+OnMcnWK5lngSzALgQYKMr9RJVOWLqQYuyn6ulqGWSXdwf6F80lQ==";
      };
    };
    "micromark-util-character-2.1.1" = {
      name = "micromark-util-character";
      packageName = "micromark-util-character";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-util-character/-/micromark-util-character-2.1.1.tgz";
        sha512 = "wv8tdUTJ3thSFFFJKtpYKOYiGP2+v96Hvk4Tu8KpCAsTMs6yi+nVmGh1syvSCsaxz45J6Jbw+9DD6g97+NV67Q==";
      };
    };
    "micromark-util-chunked-2.0.1" = {
      name = "micromark-util-chunked";
      packageName = "micromark-util-chunked";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-util-chunked/-/micromark-util-chunked-2.0.1.tgz";
        sha512 = "QUNFEOPELfmvv+4xiNg2sRYeS/P84pTW0TCgP5zc9FpXetHY0ab7SxKyAQCNCc1eK0459uoLI1y5oO5Vc1dbhA==";
      };
    };
    "micromark-util-classify-character-2.0.1" = {
      name = "micromark-util-classify-character";
      packageName = "micromark-util-classify-character";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-util-classify-character/-/micromark-util-classify-character-2.0.1.tgz";
        sha512 = "K0kHzM6afW/MbeWYWLjoHQv1sgg2Q9EccHEDzSkxiP/EaagNzCm7T/WMKZ3rjMbvIpvBiZgwR3dKMygtA4mG1Q==";
      };
    };
    "micromark-util-combine-extensions-2.0.1" = {
      name = "micromark-util-combine-extensions";
      packageName = "micromark-util-combine-extensions";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-util-combine-extensions/-/micromark-util-combine-extensions-2.0.1.tgz";
        sha512 = "OnAnH8Ujmy59JcyZw8JSbK9cGpdVY44NKgSM7E9Eh7DiLS2E9RNQf0dONaGDzEG9yjEl5hcqeIsj4hfRkLH/Bg==";
      };
    };
    "micromark-util-decode-numeric-character-reference-2.0.2" = {
      name = "micromark-util-decode-numeric-character-reference";
      packageName = "micromark-util-decode-numeric-character-reference";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-util-decode-numeric-character-reference/-/micromark-util-decode-numeric-character-reference-2.0.2.tgz";
        sha512 = "ccUbYk6CwVdkmCQMyr64dXz42EfHGkPQlBj5p7YVGzq8I7CtjXZJrubAYezf7Rp+bjPseiROqe7G6foFd+lEuw==";
      };
    };
    "micromark-util-decode-string-2.0.1" = {
      name = "micromark-util-decode-string";
      packageName = "micromark-util-decode-string";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-util-decode-string/-/micromark-util-decode-string-2.0.1.tgz";
        sha512 = "nDV/77Fj6eH1ynwscYTOsbK7rR//Uj0bZXBwJZRfaLEJ1iGBR6kIfNmlNqaqJf649EP0F3NWNdeJi03elllNUQ==";
      };
    };
    "micromark-util-encode-2.0.1" = {
      name = "micromark-util-encode";
      packageName = "micromark-util-encode";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-util-encode/-/micromark-util-encode-2.0.1.tgz";
        sha512 = "c3cVx2y4KqUnwopcO9b/SCdo2O67LwJJ/UyqGfbigahfegL9myoEFoDYZgkT7f36T0bLrM9hZTAaAyH+PCAXjw==";
      };
    };
    "micromark-util-html-tag-name-2.0.1" = {
      name = "micromark-util-html-tag-name";
      packageName = "micromark-util-html-tag-name";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-util-html-tag-name/-/micromark-util-html-tag-name-2.0.1.tgz";
        sha512 = "2cNEiYDhCWKI+Gs9T0Tiysk136SnR13hhO8yW6BGNyhOC4qYFnwF1nKfD3HFAIXA5c45RrIG1ub11GiXeYd1xA==";
      };
    };
    "micromark-util-normalize-identifier-2.0.1" = {
      name = "micromark-util-normalize-identifier";
      packageName = "micromark-util-normalize-identifier";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-util-normalize-identifier/-/micromark-util-normalize-identifier-2.0.1.tgz";
        sha512 = "sxPqmo70LyARJs0w2UclACPUUEqltCkJ6PhKdMIDuJ3gSf/Q+/GIe3WKl0Ijb/GyH9lOpUkRAO2wp0GVkLvS9Q==";
      };
    };
    "micromark-util-resolve-all-2.0.1" = {
      name = "micromark-util-resolve-all";
      packageName = "micromark-util-resolve-all";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-util-resolve-all/-/micromark-util-resolve-all-2.0.1.tgz";
        sha512 = "VdQyxFWFT2/FGJgwQnJYbe1jjQoNTS4RjglmSjTUlpUMa95Htx9NHeYW4rGDJzbjvCsl9eLjMQwGeElsqmzcHg==";
      };
    };
    "micromark-util-sanitize-uri-2.0.1" = {
      name = "micromark-util-sanitize-uri";
      packageName = "micromark-util-sanitize-uri";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-util-sanitize-uri/-/micromark-util-sanitize-uri-2.0.1.tgz";
        sha512 = "9N9IomZ/YuGGZZmQec1MbgxtlgougxTodVwDzzEouPKo3qFWvymFHWcnDi2vzV1ff6kas9ucW+o3yzJK9YB1AQ==";
      };
    };
    "micromark-util-subtokenize-2.1.0" = {
      name = "micromark-util-subtokenize";
      packageName = "micromark-util-subtokenize";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-util-subtokenize/-/micromark-util-subtokenize-2.1.0.tgz";
        sha512 = "XQLu552iSctvnEcgXw6+Sx75GflAPNED1qx7eBJ+wydBb2KCbRZe+NwvIEEMM83uml1+2WSXpBAcp9IUCgCYWA==";
      };
    };
    "micromark-util-symbol-2.0.1" = {
      name = "micromark-util-symbol";
      packageName = "micromark-util-symbol";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-util-symbol/-/micromark-util-symbol-2.0.1.tgz";
        sha512 = "vs5t8Apaud9N28kgCrRUdEed4UJ+wWNvicHLPxCa9ENlYuAY31M0ETy5y1vA33YoNPDFTghEbnh6efaE8h4x0Q==";
      };
    };
    "micromark-util-types-2.0.2" = {
      name = "micromark-util-types";
      packageName = "micromark-util-types";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-util-types/-/micromark-util-types-2.0.2.tgz";
        sha512 = "Yw0ECSpJoViF1qTU4DC6NwtC4aWGt1EkzaQB8KPPyCRR8z9TWeV0HbEFGTO+ZY1wB22zmxnJqhPyTpOVCpeHTA==";
      };
    };
    "ms-2.1.3" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.3.tgz";
        sha512 = "6FlzubTLZG3J2a/NVCAleEhjzq5oxgHyaCU9yYXvcLsvoVaHJq/s5xXI6/XXP6tz7R9xAOtHnSO/tXtF3WRTlA==";
      };
    };
    "muggle-string-0.4.1" = {
      name = "muggle-string";
      packageName = "muggle-string";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/muggle-string/-/muggle-string-0.4.1.tgz";
        sha512 = "VNTrAak/KhO2i8dqqnqnAHOa3cYBwXEZe9h+D5h/1ZqFSTEFHdM65lR7RoIqq3tBBYavsOXV84NoHXZ0AkPyqQ==";
      };
    };
    "nanoid-3.3.11" = {
      name = "nanoid";
      packageName = "nanoid";
      version = "3.3.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanoid/-/nanoid-3.3.11.tgz";
        sha512 = "N8SpfPUnUp1bK+PMYW8qSWdl9U+wwNWI4QKxOYDy9JAro3WMX7p2OeVRF9v+347pnakNevPmiHhNmZ2HbFA76w==";
      };
    };
    "node-releases-2.0.26" = {
      name = "node-releases";
      packageName = "node-releases";
      version = "2.0.26";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-releases/-/node-releases-2.0.26.tgz";
        sha512 = "S2M9YimhSjBSvYnlr5/+umAnPHE++ODwt5e2Ij6FoX45HA/s4vHdkDx1eax2pAPeAOqu4s9b7ppahsyEFdVqQA==";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha512 = "rJgTQnkUnH1sFw8yT6VSU3zD3sWmu6sZhIseY8VX+GRu3P6F7Fu+JNDoXfklElbLJSnc3FUQHVe4cU5hj+BcUg==";
      };
    };
    "ohm-js-17.2.1" = {
      name = "ohm-js";
      packageName = "ohm-js";
      version = "17.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ohm-js/-/ohm-js-17.2.1.tgz";
        sha512 = "4cXF0G09fAYU9z61kTfkNbKK1Kz/sGEZ5NbVWHoe9Qi7VB7y+Spwk051CpUTfUENdlIr+vt8tMV4/LosTE2cDQ==";
      };
    };
    "oxc-parser-0.74.0" = {
      name = "oxc-parser";
      packageName = "oxc-parser";
      version = "0.74.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/oxc-parser/-/oxc-parser-0.74.0.tgz";
        sha512 = "2tDN/ttU8WE6oFh8EzKNam7KE7ZXSG5uXmvX85iNzxdJfMssDWcj3gpYzZi1E04XuE7m3v1dVWl/8BE886vPGw==";
      };
    };
    "path-browserify-1.0.1" = {
      name = "path-browserify";
      packageName = "path-browserify";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-browserify/-/path-browserify-1.0.1.tgz";
        sha512 = "b7uo2UCUOYZcnF/3ID0lulOJi/bafxa1xPe7ZPsammBSpjSWQkjNxlt635YGS2MiR9GjvuXCtz2emr3jbsz98g==";
      };
    };
    "picocolors-1.1.1" = {
      name = "picocolors";
      packageName = "picocolors";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/picocolors/-/picocolors-1.1.1.tgz";
        sha512 = "xceH2snhtb5M9liqDsmEw56le376mTZkEX/jEb/RxNFyegNul7eNslCXP9FDj/Lcu0X8KEyMceP2ntpaHrDEVA==";
      };
    };
    "picomatch-4.0.3" = {
      name = "picomatch";
      packageName = "picomatch";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/picomatch/-/picomatch-4.0.3.tgz";
        sha512 = "5gTmgEY/sqK6gFXLIsQNH19lWb4ebPDLA4SdLP7dsWkIXHWlG66oPuVvXSGFPppYZz8ZDZq0dYYrbHfBCVUb1Q==";
      };
    };
    "postcss-8.5.6" = {
      name = "postcss";
      packageName = "postcss";
      version = "8.5.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss/-/postcss-8.5.6.tgz";
        sha512 = "3Ybi1tAuwAP9s0r1UQ2J4n5Y0G05bJkpUIO0/bI9MhwmD70S5aTWbXGBwxHrelT+XM1k6dM0pk+SwNkpTRN7Pg==";
      };
    };
    "postcss-less-6.0.0" = {
      name = "postcss-less";
      packageName = "postcss-less";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-less/-/postcss-less-6.0.0.tgz";
        sha512 = "FPX16mQLyEjLzEuuJtxA8X3ejDLNGGEG503d2YGZR5Ask1SpDN8KmZUMpzCvyalWRywAn1n1VOA5dcqfCLo5rg==";
      };
    };
    "postcss-scss-4.0.9" = {
      name = "postcss-scss";
      packageName = "postcss-scss";
      version = "4.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-scss/-/postcss-scss-4.0.9.tgz";
        sha512 = "AjKOeiwAitL/MXxQW2DliT28EKukvvbEWx3LBmJIRN8KfBGZbRTxNYW0kSqi1COiTZ57nZ9NW06S6ux//N1c9A==";
      };
    };
    "prettier-3.6.2" = {
      name = "prettier";
      packageName = "prettier";
      version = "3.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/prettier/-/prettier-3.6.2.tgz";
        sha512 = "I7AIg5boAr5R0FFtJ6rCfD+LFsWHp81dolrFD8S79U9tb8Az2nGrJncnMSnys+bpQJfRUzqs9hnA81OAA3hCuQ==";
      };
    };
    "prettier-plugin-astro-0.14.1" = {
      name = "prettier-plugin-astro";
      packageName = "prettier-plugin-astro";
      version = "0.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/prettier-plugin-astro/-/prettier-plugin-astro-0.14.1.tgz";
        sha512 = "RiBETaaP9veVstE4vUwSIcdATj6dKmXljouXc/DDNwBSPTp8FRkLGDSGFClKsAFeeg+13SB0Z1JZvbD76bigJw==";
      };
    };
    "prettier-plugin-css-order-2.1.2" = {
      name = "prettier-plugin-css-order";
      packageName = "prettier-plugin-css-order";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/prettier-plugin-css-order/-/prettier-plugin-css-order-2.1.2.tgz";
        sha512 = "vomxPjHI6pOMYcBuouSJHxxQClJXaUpU9rsV9IAO2wrSTZILRRlrxAAR8t9UF6wtczLkLfNRFUwM+ZbGXOONUA==";
      };
    };
    "prettier-plugin-ember-template-tag-2.1.0" = {
      name = "prettier-plugin-ember-template-tag";
      packageName = "prettier-plugin-ember-template-tag";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/prettier-plugin-ember-template-tag/-/prettier-plugin-ember-template-tag-2.1.0.tgz";
        sha512 = "Ium+m2zHSZKzRFt1Shn+sv8j1BzfFWP3E0tZeKTKP1U7v/tMyLuQNBRyRCJ7REdKc9bWkIJG/hCSf0CKqCVU1w==";
      };
    };
    "prettier-plugin-jsdoc-1.3.3" = {
      name = "prettier-plugin-jsdoc";
      packageName = "prettier-plugin-jsdoc";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/prettier-plugin-jsdoc/-/prettier-plugin-jsdoc-1.3.3.tgz";
        sha512 = "YIxejcbPYK4N58jHGiXjYvrCzBMyvV2AEMSoF5LvqqeMEI0nsmww57I6NGnpVc0AU9ncFCTEBoYHN/xuBf80YA==";
      };
    };
    "prettier-plugin-marko-3.3.2" = {
      name = "prettier-plugin-marko";
      packageName = "prettier-plugin-marko";
      version = "3.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/prettier-plugin-marko/-/prettier-plugin-marko-3.3.2.tgz";
        sha512 = "2ZNi4FquozTs3INTLRP5KsNF/XuMNrjTKS2wMvsoVNR7cFDjv8KgNR0uke8yL9ZqgRveVdaDy5UNPFqMhXRQPA==";
      };
    };
    "prettier-plugin-multiline-arrays-4.0.3" = {
      name = "prettier-plugin-multiline-arrays";
      packageName = "prettier-plugin-multiline-arrays";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/prettier-plugin-multiline-arrays/-/prettier-plugin-multiline-arrays-4.0.3.tgz";
        sha512 = "H1f/0zbvlO/FR0Fmyl31sSBodsIZkuQF0Omi9BrptLU31rZ+Almt9BbrE8IS3BFT/DGKePKb55XqN660LTnmsQ==";
      };
    };
    "prettier-plugin-organize-attributes-1.0.0" = {
      name = "prettier-plugin-organize-attributes";
      packageName = "prettier-plugin-organize-attributes";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/prettier-plugin-organize-attributes/-/prettier-plugin-organize-attributes-1.0.0.tgz";
        sha512 = "+NmameaLxbCcylEXsKPmawtzla5EE6ECqvGkpfQz4KM847fXDifB1gFnPQEpoADAq6IXg+cMI8Z0ISJEXa6fhg==";
      };
    };
    "prettier-plugin-organize-imports-4.3.0" = {
      name = "prettier-plugin-organize-imports";
      packageName = "prettier-plugin-organize-imports";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/prettier-plugin-organize-imports/-/prettier-plugin-organize-imports-4.3.0.tgz";
        sha512 = "FxFz0qFhyBsGdIsb697f/EkvHzi5SZOhWAjxcx2dLt+Q532bAlhswcXGYB1yzjZ69kW8UoadFBw7TyNwlq96Iw==";
      };
    };
    "prettier-plugin-sort-imports-1.8.8" = {
      name = "prettier-plugin-sort-imports";
      packageName = "prettier-plugin-sort-imports";
      version = "1.8.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/prettier-plugin-sort-imports/-/prettier-plugin-sort-imports-1.8.8.tgz";
        sha512 = "Qqzt4nGF867zyk500YnnRhO9bqyiTiYIxgA8q3Pkxoa3BEqNCA+yB9kAFv2L3B5olEV1nBsfdwYAwyORrzQUNw==";
      };
    };
    "prettier-plugin-svelte-3.4.0" = {
      name = "prettier-plugin-svelte";
      packageName = "prettier-plugin-svelte";
      version = "3.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/prettier-plugin-svelte/-/prettier-plugin-svelte-3.4.0.tgz";
        sha512 = "pn1ra/0mPObzqoIQn/vUTR3ZZI6UuZ0sHqMK5x2jMLGrs53h0sXhkVuDcrlssHwIMk7FYrMjHBPoUSyyEEDlBQ==";
      };
    };
    "proxy-vir-2.0.1" = {
      name = "proxy-vir";
      packageName = "proxy-vir";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/proxy-vir/-/proxy-vir-2.0.1.tgz";
        sha512 = "hjy5mWzHZhgRGh0f90f0Bz3VrGUe0T+AlhwnETakzRdvaN9RtPYLQG1+ZuEzSDK95FAhPYd26nEi1xVrXqvBwg==";
      };
    };
    "pug-error-2.1.0" = {
      name = "pug-error";
      packageName = "pug-error";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-error/-/pug-error-2.1.0.tgz";
        sha512 = "lv7sU9e5Jk8IeUheHata6/UThZ7RK2jnaaNztxfPYUY+VxZyk/ePVaNZ/vwmH8WqGvDz3LrNYt/+gA55NDg6Pg==";
      };
    };
    "pug-lexer-5.0.1" = {
      name = "pug-lexer";
      packageName = "pug-lexer";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-lexer/-/pug-lexer-5.0.1.tgz";
        sha512 = "0I6C62+keXlZPZkOJeVam9aBLVP2EnbeDw3An+k0/QlqdwH6rv8284nko14Na7c0TtqtogfWXcRoFE4O4Ff20w==";
      };
    };
    "raptor-async-1.1.3" = {
      name = "raptor-async";
      packageName = "raptor-async";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/raptor-async/-/raptor-async-1.1.3.tgz";
        sha512 = "VZCxygWMjW9lKqnApK9D2QbfyzRn7ehiTqnXWwMCLBXANSy+xbnYfbX/5f8YX3bZXu+g+JESmqWPchIQrZj2ig==";
      };
    };
    "raptor-regexp-1.0.1" = {
      name = "raptor-regexp";
      packageName = "raptor-regexp";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/raptor-regexp/-/raptor-regexp-1.0.1.tgz";
        sha512 = "DqC7ViHJUs3jLIxJI1/HVvCu3yPJaP8CM7PGsHvjimg7yJ3lLOdCBxlPE0G2Q8OJgUA8Pe7nvhm6lcQ3hZepow==";
      };
    };
    "raptor-util-3.2.0" = {
      name = "raptor-util";
      packageName = "raptor-util";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/raptor-util/-/raptor-util-3.2.0.tgz";
        sha512 = "uEDMMkBCJvjTqYMBnJNxn+neiS6a0rhybQNA9RaexGor1uvKjwyHA5VcbZMZEuqXhKUWbL+WNS7PhuZVZNB7pw==";
      };
    };
    "relative-import-path-1.0.0" = {
      name = "relative-import-path";
      packageName = "relative-import-path";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/relative-import-path/-/relative-import-path-1.0.0.tgz";
        sha512 = "ZvbtoduKQmD4PZeJPfH6Ql21qUWhaMxiHkIsH+FUnZqKDwNIXBtGg5zRZyHWomiGYk8n5+KMBPK7Mi4D0XWfNg==";
      };
    };
    "resolve-from-5.0.0" = {
      name = "resolve-from";
      packageName = "resolve-from";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-from/-/resolve-from-5.0.0.tgz";
        sha512 = "qYg9KP24dD5qka9J47d0aVky0N+b4fTU89LN9iDnjB5waksiC49rvMB0PrUJQGoTmH50XPiqOvAjDfaijGxYZw==";
      };
    };
    "s.color-0.0.15" = {
      name = "s.color";
      packageName = "s.color";
      version = "0.0.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/s.color/-/s.color-0.0.15.tgz";
        sha512 = "AUNrbEUHeKY8XsYr/DYpl+qk5+aM+DChopnWOPEzn8YKzOhv4l2zH6LzZms3tOZP3wwdOyc0RmTciyi46HLIuA==";
      };
    };
    "sass-formatter-0.7.9" = {
      name = "sass-formatter";
      packageName = "sass-formatter";
      version = "0.7.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/sass-formatter/-/sass-formatter-0.7.9.tgz";
        sha512 = "CWZ8XiSim+fJVG0cFLStwDvft1VI7uvXdCNJYXhDvowiv+DsbD1nXLiQ4zrE5UBvj5DWZJ93cwN0NX5PMsr1Pw==";
      };
    };
    "self-closing-tags-1.0.1" = {
      name = "self-closing-tags";
      packageName = "self-closing-tags";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/self-closing-tags/-/self-closing-tags-1.0.1.tgz";
        sha512 = "7t6hNbYMxM+VHXTgJmxwgZgLGktuXtVVD5AivWzNTdJBM4DBjnDKDzkf2SrNjihaArpeJYNjxkELBu1evI4lQA==";
      };
    };
    "semver-6.3.1" = {
      name = "semver";
      packageName = "semver";
      version = "6.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-6.3.1.tgz";
        sha512 = "BR7VvDCVHO+q2xBEWskxS6DJE1qRnb7DxzUrogb71CWoSficBxYsiAGd+Kl0mmq/MprG9yArRkyrQxTO6XjMzA==";
      };
    };
    "semver-7.7.3" = {
      name = "semver";
      packageName = "semver";
      version = "7.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.7.3.tgz";
        sha512 = "SdsKMrI9TdgjdweUSR9MweHA4EJ8YxHn8DFaDisvhVlUOe4BF1tLD7GAj0lIqWVl+dPb/rExr0Btby5loQm20Q==";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==";
      };
    };
    "source-map-js-1.2.1" = {
      name = "source-map-js";
      packageName = "source-map-js";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-js/-/source-map-js-1.2.1.tgz";
        sha512 = "UXWMKhLOwVKb728IUtQPXxfYU+usdybtUrK/8uGE8CQMvrhOpwvzDBwj0QhSL7MQc7vIsISBG8VQ8+IDQxpfQA==";
      };
    };
    "source-map-support-0.5.21" = {
      name = "source-map-support";
      packageName = "source-map-support";
      version = "0.5.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-support/-/source-map-support-0.5.21.tgz";
        sha512 = "uBHU3L3czsIyYXKX88fdrGovxdSCoTGDRZ6SYXtSRxLZUzHg5P/66Ht6uoUlHu9EZod+inXhKo3qQgwXUT/y1w==";
      };
    };
    "stackframe-1.3.4" = {
      name = "stackframe";
      packageName = "stackframe";
      version = "1.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/stackframe/-/stackframe-1.3.4.tgz";
        sha512 = "oeVtt7eWQS+Na6F//S4kJ2K2VbRlS9D43mAlMyVpVWovy9o+jfgH8O9agzANzaiLjclA0oYzUXEM4PurhSUChw==";
      };
    };
    "suf-log-2.5.3" = {
      name = "suf-log";
      packageName = "suf-log";
      version = "2.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/suf-log/-/suf-log-2.5.3.tgz";
        sha512 = "KvC8OPjzdNOe+xQ4XWJV2whQA0aM1kGVczMQ8+dStAO6KfEB140JEVQ9dE76ONZ0/Ylf67ni4tILPJB41U0eow==";
      };
    };
    "svelte-5.41.2" = {
      name = "svelte";
      packageName = "svelte";
      version = "5.41.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/svelte/-/svelte-5.41.2.tgz";
        sha512 = "JetVllvRzfAqg/32ST3SWkb0+OiCpJ/sSMTe206QgiTAN6XaCR3s7nx2L+hQHoUd/1YoK+UsEblGWyKcqY7Efg==";
      };
    };
    "tagged-tag-1.0.0" = {
      name = "tagged-tag";
      packageName = "tagged-tag";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tagged-tag/-/tagged-tag-1.0.0.tgz";
        sha512 = "yEFYrVhod+hdNyx7g5Bnkkb0G6si8HJurOoOEgC8B/O0uXLHlaey/65KRv6cuWBNhBgHKAROVpc7QyYqE5gFng==";
      };
    };
    "type-fest-5.1.0" = {
      name = "type-fest";
      packageName = "type-fest";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-fest/-/type-fest-5.1.0.tgz";
        sha512 = "wQ531tuWvB6oK+pchHIu5lHe5f5wpSCqB8Kf4dWQRbOYc9HTge7JL0G4Qd44bh6QuJCccIzL3bugb8GI0MwHrg==";
      };
    };
    "typed-event-target-4.1.0" = {
      name = "typed-event-target";
      packageName = "typed-event-target";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/typed-event-target/-/typed-event-target-4.1.0.tgz";
        sha512 = "fDFhZb7ofywLsVv8mYePD6ONfCpVHyM1t2dboEJx/XMsnflljnu3GQ5qH09hS1USuypGMR7wRbdWQPydgJ8nGQ==";
      };
    };
    "typescript-5.9.3" = {
      name = "typescript";
      packageName = "typescript";
      version = "5.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript/-/typescript-5.9.3.tgz";
        sha512 = "jl1vZzPDinLr9eUt3J/t7V6FgNEw9QjvBPdysz9KfQDD41fQrC2Y4vKQdiaUpFT4bXlb1RHhLpp8wtm6M5TgSw==";
      };
    };
    "unist-util-stringify-position-4.0.0" = {
      name = "unist-util-stringify-position";
      packageName = "unist-util-stringify-position";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unist-util-stringify-position/-/unist-util-stringify-position-4.0.0.tgz";
        sha512 = "0ASV06AAoKCDkS2+xw5RXJywruurpbC4JZSm7nr7MOt1ojAzvyyaO+UxZf18j8FCF6kmzCZKcAgN/yu2gm2XgQ==";
      };
    };
    "update-browserslist-db-1.1.4" = {
      name = "update-browserslist-db";
      packageName = "update-browserslist-db";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/update-browserslist-db/-/update-browserslist-db-1.1.4.tgz";
        sha512 = "q0SPT4xyU84saUX+tomz1WLkxUbuaJnR1xWt17M7fJtEJigJeWUNGUqrauFXsHnqev9y9JTRGwk13tFBuKby4A==";
      };
    };
    "vscode-uri-3.1.0" = {
      name = "vscode-uri";
      packageName = "vscode-uri";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-uri/-/vscode-uri-3.1.0.tgz";
        sha512 = "/BpdSx+yCQGnCvecbyXdxHDkuk55/G3xwnC0GqY4gmQ3j+A+g8kzzgB4Nk/SINjqn6+waqw3EgbVF2QKExkRxQ==";
      };
    };
    "vue-tsc-3.1.1" = {
      name = "vue-tsc";
      packageName = "vue-tsc";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vue-tsc/-/vue-tsc-3.1.1.tgz";
        sha512 = "fyixKxFniOVgn+L/4+g8zCG6dflLLt01Agz9jl3TO45Bgk87NZJRmJVPsiK+ouq3LB91jJCbOV+pDkzYTxbI7A==";
      };
    };
    "yallist-3.1.1" = {
      name = "yallist";
      packageName = "yallist";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-3.1.1.tgz";
        sha512 = "a4UGQaWPH59mOXUYnAG2ewncQS4i4F43Tv3JoAM+s2VDAmS9NsK8GpDMLrCHPksFT7h3K6TOoUNn2pb7RoXx4g==";
      };
    };
    "zimmerframe-1.1.4" = {
      name = "zimmerframe";
      packageName = "zimmerframe";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/zimmerframe/-/zimmerframe-1.1.4.tgz";
        sha512 = "B58NGBEoc8Y9MWWCQGl/gq9xBCe4IiKM0a2x7GZdQKOW5Exr8S1W24J6OgM1njK8xCRGvAJIL/MxXHf6SkmQKQ==";
      };
    };
  };
in
{
  prettier-plugin-tailwindcss = nodeEnv.buildNodePackage {
    name = "prettier-plugin-tailwindcss";
    packageName = "prettier-plugin-tailwindcss";
    version = "0.7.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/prettier-plugin-tailwindcss/-/prettier-plugin-tailwindcss-0.7.1.tgz";
      sha512 = "Bzv1LZcuiR1Sk02iJTS1QzlFNp/o5l2p3xkopwOrbPmtMeh3fK9rVW5M3neBQzHq+kGKj/4LGQMTNcTH4NGPtQ==";
    };
    dependencies = [
      sources."@astrojs/compiler-2.13.0"
      sources."@augment-vir/assert-31.43.0"
      sources."@augment-vir/common-31.43.0"
      sources."@augment-vir/core-31.43.0"
      sources."@babel/code-frame-7.27.1"
      sources."@babel/compat-data-7.28.4"
      (sources."@babel/core-7.28.4" // {
        dependencies = [
          sources."semver-6.3.1"
        ];
      })
      sources."@babel/generator-7.28.3"
      sources."@babel/helper-annotate-as-pure-7.27.3"
      (sources."@babel/helper-compilation-targets-7.27.2" // {
        dependencies = [
          sources."semver-6.3.1"
        ];
      })
      (sources."@babel/helper-create-class-features-plugin-7.28.3" // {
        dependencies = [
          sources."semver-6.3.1"
        ];
      })
      sources."@babel/helper-globals-7.28.0"
      sources."@babel/helper-member-expression-to-functions-7.27.1"
      sources."@babel/helper-module-imports-7.27.1"
      sources."@babel/helper-module-transforms-7.28.3"
      sources."@babel/helper-optimise-call-expression-7.27.1"
      sources."@babel/helper-plugin-utils-7.27.1"
      sources."@babel/helper-replace-supers-7.27.1"
      sources."@babel/helper-skip-transparent-expression-wrappers-7.27.1"
      sources."@babel/helper-string-parser-7.27.1"
      sources."@babel/helper-validator-identifier-7.27.1"
      sources."@babel/helper-validator-option-7.27.1"
      sources."@babel/helpers-7.28.4"
      sources."@babel/parser-7.28.4"
      sources."@babel/plugin-syntax-typescript-7.27.1"
      sources."@babel/plugin-transform-modules-commonjs-7.27.1"
      sources."@babel/plugin-transform-typescript-7.28.0"
      sources."@babel/runtime-7.28.4"
      sources."@babel/template-7.27.2"
      sources."@babel/traverse-7.28.4"
      sources."@babel/types-7.28.4"
      sources."@date-vir/duration-8.0.0"
      sources."@ianvs/prettier-plugin-sort-imports-4.7.0"
      sources."@jridgewell/gen-mapping-0.3.13"
      sources."@jridgewell/remapping-2.3.5"
      sources."@jridgewell/resolve-uri-3.1.2"
      sources."@jridgewell/sourcemap-codec-1.5.5"
      sources."@jridgewell/trace-mapping-0.3.31"
      sources."@luxass/strip-json-comments-1.4.0"
      sources."@marko/compiler-5.39.40"
      sources."@oxc-project/types-0.74.0"
      sources."@prettier/plugin-hermes-0.0.3"
      sources."@prettier/plugin-oxc-0.0.4"
      sources."@prettier/plugin-pug-3.4.2"
      sources."@shopify/liquid-html-parser-2.9.0"
      sources."@shopify/prettier-plugin-liquid-1.10.0"
      (sources."@sveltejs/acorn-typescript-1.0.6" // {
        dependencies = [
          sources."acorn-8.15.0"
        ];
      })
      sources."@trivago/prettier-plugin-sort-imports-5.2.2"
      sources."@types/debug-4.1.12"
      sources."@types/estree-1.0.8"
      sources."@types/luxon-3.7.1"
      sources."@types/mdast-4.0.4"
      sources."@types/ms-2.1.0"
      sources."@types/unist-3.0.3"
      sources."@volar/language-core-2.4.23"
      sources."@volar/source-map-2.4.23"
      sources."@volar/typescript-2.4.23"
      sources."@vue/compiler-core-3.5.22"
      sources."@vue/compiler-dom-3.5.22"
      sources."@vue/compiler-sfc-3.5.22"
      sources."@vue/compiler-ssr-3.5.22"
      sources."@vue/language-core-3.1.1"
      sources."@vue/shared-3.5.22"
      sources."@zackad/prettier-plugin-twig-0.16.0"
      sources."acorn-7.4.1"
      sources."alien-signals-3.0.3"
      sources."ansi-styles-6.2.3"
      sources."aria-query-5.3.2"
      sources."async-function-1.0.0"
      sources."async-generator-function-1.0.0"
      sources."axobject-query-4.1.0"
      sources."baseline-browser-mapping-2.8.19"
      sources."binary-searching-2.0.5"
      sources."browser-or-node-3.0.0"
      sources."browserslist-4.27.0"
      sources."buffer-from-1.1.2"
      sources."call-bind-apply-helpers-1.0.2"
      sources."call-bound-1.0.4"
      sources."caniuse-lite-1.0.30001751"
      sources."character-entities-2.0.2"
      sources."character-parser-2.2.0"
      sources."clsx-2.1.1"
      sources."comment-parser-1.4.1"
      sources."complain-1.6.1"
      sources."content-tag-4.0.0"
      sources."convert-source-map-2.0.0"
      sources."css-declaration-sorter-7.3.0"
      sources."debug-4.4.3"
      sources."decode-named-character-reference-1.2.0"
      sources."deep-eql-5.0.2"
      sources."deepcopy-esm-2.1.1"
      sources."dequal-2.0.3"
      sources."devlop-1.1.0"
      sources."diff-8.0.2"
      sources."dunder-proto-1.0.1"
      sources."electron-to-chromium-1.5.238"
      sources."entities-4.5.0"
      sources."error-stack-parser-2.1.4"
      sources."es-define-property-1.0.1"
      sources."es-errors-1.3.0"
      sources."es-object-atoms-1.1.1"
      sources."escalade-3.2.0"
      sources."esm-env-1.2.2"
      sources."esrap-2.1.0"
      sources."estree-walker-2.0.2"
      sources."expect-type-1.2.2"
      sources."function-bind-1.1.2"
      sources."generator-function-2.0.1"
      sources."gensync-1.0.0-beta.2"
      sources."get-intrinsic-1.3.1"
      sources."get-proto-1.0.1"
      sources."gopd-1.2.0"
      sources."has-symbols-1.1.0"
      sources."has-tostringtag-1.0.2"
      sources."hasown-2.0.2"
      sources."he-1.2.0"
      sources."html-styles-1.0.0"
      sources."htmljs-parser-5.7.4"
      sources."is-expression-4.0.0"
      sources."is-reference-3.0.3"
      sources."is-regex-1.2.1"
      sources."isarray-1.0.0"
      sources."isobject-2.1.0"
      sources."javascript-natural-sort-0.7.1"
      sources."js-tokens-4.0.0"
      sources."jsesc-3.1.0"
      sources."json5-2.2.3"
      sources."kleur-4.1.5"
      sources."lasso-caching-fs-1.0.2"
      sources."lasso-package-root-1.0.1"
      sources."line-column-1.0.2"
      sources."locate-character-3.0.0"
      sources."lodash-4.17.21"
      sources."lru-cache-5.1.1"
      sources."luxon-3.7.2"
      sources."magic-string-0.30.19"
      sources."math-intrinsics-1.1.0"
      sources."mdast-util-from-markdown-2.0.2"
      sources."mdast-util-to-string-4.0.0"
      sources."micromark-4.0.2"
      sources."micromark-core-commonmark-2.0.3"
      sources."micromark-factory-destination-2.0.1"
      sources."micromark-factory-label-2.0.1"
      sources."micromark-factory-space-2.0.1"
      sources."micromark-factory-title-2.0.1"
      sources."micromark-factory-whitespace-2.0.1"
      sources."micromark-util-character-2.1.1"
      sources."micromark-util-chunked-2.0.1"
      sources."micromark-util-classify-character-2.0.1"
      sources."micromark-util-combine-extensions-2.0.1"
      sources."micromark-util-decode-numeric-character-reference-2.0.2"
      sources."micromark-util-decode-string-2.0.1"
      sources."micromark-util-encode-2.0.1"
      sources."micromark-util-html-tag-name-2.0.1"
      sources."micromark-util-normalize-identifier-2.0.1"
      sources."micromark-util-resolve-all-2.0.1"
      sources."micromark-util-sanitize-uri-2.0.1"
      sources."micromark-util-subtokenize-2.1.0"
      sources."micromark-util-symbol-2.0.1"
      sources."micromark-util-types-2.0.2"
      sources."ms-2.1.3"
      sources."muggle-string-0.4.1"
      sources."nanoid-3.3.11"
      sources."node-releases-2.0.26"
      sources."object-assign-4.1.1"
      sources."ohm-js-17.2.1"
      sources."oxc-parser-0.74.0"
      sources."path-browserify-1.0.1"
      sources."picocolors-1.1.1"
      sources."picomatch-4.0.3"
      sources."postcss-8.5.6"
      sources."postcss-less-6.0.0"
      sources."postcss-scss-4.0.9"
      sources."prettier-3.6.2"
      sources."prettier-plugin-astro-0.14.1"
      sources."prettier-plugin-css-order-2.1.2"
      sources."prettier-plugin-ember-template-tag-2.1.0"
      sources."prettier-plugin-jsdoc-1.3.3"
      sources."prettier-plugin-marko-3.3.2"
      sources."prettier-plugin-multiline-arrays-4.0.3"
      sources."prettier-plugin-organize-attributes-1.0.0"
      sources."prettier-plugin-organize-imports-4.3.0"
      sources."prettier-plugin-sort-imports-1.8.8"
      sources."prettier-plugin-svelte-3.4.0"
      sources."proxy-vir-2.0.1"
      sources."pug-error-2.1.0"
      sources."pug-lexer-5.0.1"
      sources."raptor-async-1.1.3"
      sources."raptor-regexp-1.0.1"
      sources."raptor-util-3.2.0"
      sources."relative-import-path-1.0.0"
      sources."resolve-from-5.0.0"
      sources."s.color-0.0.15"
      sources."sass-formatter-0.7.9"
      sources."self-closing-tags-1.0.1"
      sources."semver-7.7.3"
      sources."source-map-0.6.1"
      sources."source-map-js-1.2.1"
      sources."source-map-support-0.5.21"
      sources."stackframe-1.3.4"
      sources."suf-log-2.5.3"
      (sources."svelte-5.41.2" // {
        dependencies = [
          sources."acorn-8.15.0"
        ];
      })
      sources."tagged-tag-1.0.0"
      sources."type-fest-5.1.0"
      sources."typed-event-target-4.1.0"
      sources."typescript-5.9.3"
      sources."unist-util-stringify-position-4.0.0"
      sources."update-browserslist-db-1.1.4"
      sources."vscode-uri-3.1.0"
      sources."vue-tsc-3.1.1"
      sources."yallist-3.1.1"
      sources."zimmerframe-1.1.4"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A Prettier plugin for sorting Tailwind CSS classes.";
      homepage = "https://github.com/tailwindlabs/prettier-plugin-tailwindcss#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
