definitions:
  status.Status:
    properties:
      uptime:
        description: Indicates the duration of the service uptime
        type: integer
      version:
        description: Version of the service
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/status:
    get:
      description: Returns version and uptime
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/status.Status'
      summary: Status page for the API
      tags:
      - Health
swagger: "2.0"
