name: Style

on:
  pull_request:
    paths:
      - "frontend/**"
      - "backend/**"
      - ".github/workflows/style-checks.yml"
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - "backend/**"
      - ".github/workflows/style-checks.yml"

jobs:
  flake-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: nix flake check
      run: nix flake check -L --accept-flake-config

  lint-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
      - run: npm ci
      - run: npm run lint

  lint-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          install-mode: goinstall
          args: --timeout=5m
          working-directory: backend
